// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_ap_fixed_ap_fixed_16_6_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [14:0] data_0_V_read;
input  [14:0] data_1_V_read;
input  [14:0] data_2_V_read;
input  [14:0] data_3_V_read;
input  [14:0] data_4_V_read;
input  [14:0] data_5_V_read;
input  [14:0] data_6_V_read;
input  [14:0] data_7_V_read;
input  [14:0] data_8_V_read;
input  [14:0] data_9_V_read;
input  [14:0] data_10_V_read;
input  [14:0] data_11_V_read;
input  [14:0] data_12_V_read;
input  [14:0] data_13_V_read;
input  [14:0] data_14_V_read;
input  [14:0] data_15_V_read;
input  [14:0] data_16_V_read;
input  [14:0] data_17_V_read;
input  [14:0] data_18_V_read;
input  [14:0] data_19_V_read;
input  [14:0] data_20_V_read;
input  [14:0] data_21_V_read;
input  [14:0] data_22_V_read;
input  [14:0] data_23_V_read;
input  [14:0] data_24_V_read;
input  [14:0] data_25_V_read;
input  [14:0] data_26_V_read;
input  [14:0] data_27_V_read;
input  [14:0] data_28_V_read;
input  [14:0] data_29_V_read;
input  [14:0] data_30_V_read;
input  [14:0] data_31_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln64_fu_1345_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] w11_V_address0;
reg    w11_V_ce0;
wire   [155:0] w11_V_q0;
reg   [0:0] do_init_reg_369;
reg   [14:0] data_0_V_read14_rewind_reg_385;
reg   [14:0] data_1_V_read15_rewind_reg_399;
reg   [14:0] data_2_V_read16_rewind_reg_413;
reg   [14:0] data_3_V_read17_rewind_reg_427;
reg   [14:0] data_4_V_read18_rewind_reg_441;
reg   [14:0] data_5_V_read19_rewind_reg_455;
reg   [14:0] data_6_V_read20_rewind_reg_469;
reg   [14:0] data_7_V_read21_rewind_reg_483;
reg   [14:0] data_8_V_read22_rewind_reg_497;
reg   [14:0] data_9_V_read23_rewind_reg_511;
reg   [14:0] data_10_V_read24_rewind_reg_525;
reg   [14:0] data_11_V_read25_rewind_reg_539;
reg   [14:0] data_12_V_read26_rewind_reg_553;
reg   [14:0] data_13_V_read27_rewind_reg_567;
reg   [14:0] data_14_V_read28_rewind_reg_581;
reg   [14:0] data_15_V_read29_rewind_reg_595;
reg   [14:0] data_16_V_read30_rewind_reg_609;
reg   [14:0] data_17_V_read31_rewind_reg_623;
reg   [14:0] data_18_V_read32_rewind_reg_637;
reg   [14:0] data_19_V_read33_rewind_reg_651;
reg   [14:0] data_20_V_read34_rewind_reg_665;
reg   [14:0] data_21_V_read35_rewind_reg_679;
reg   [14:0] data_22_V_read36_rewind_reg_693;
reg   [14:0] data_23_V_read37_rewind_reg_707;
reg   [14:0] data_24_V_read38_rewind_reg_721;
reg   [14:0] data_25_V_read39_rewind_reg_735;
reg   [14:0] data_26_V_read40_rewind_reg_749;
reg   [14:0] data_27_V_read41_rewind_reg_763;
reg   [14:0] data_28_V_read42_rewind_reg_777;
reg   [14:0] data_29_V_read43_rewind_reg_791;
reg   [14:0] data_30_V_read44_rewind_reg_805;
reg   [14:0] data_31_V_read45_rewind_reg_819;
reg   [3:0] w_index13_reg_833;
reg   [14:0] data_0_V_read14_phi_reg_848;
reg   [14:0] data_1_V_read15_phi_reg_861;
reg   [14:0] data_2_V_read16_phi_reg_874;
reg   [14:0] data_3_V_read17_phi_reg_887;
reg   [14:0] data_4_V_read18_phi_reg_900;
reg   [14:0] data_5_V_read19_phi_reg_913;
reg   [14:0] data_6_V_read20_phi_reg_926;
reg   [14:0] data_7_V_read21_phi_reg_939;
reg   [14:0] data_8_V_read22_phi_reg_952;
reg   [14:0] data_9_V_read23_phi_reg_965;
reg   [14:0] data_10_V_read24_phi_reg_978;
reg   [14:0] data_11_V_read25_phi_reg_991;
reg   [14:0] data_12_V_read26_phi_reg_1004;
reg   [14:0] data_13_V_read27_phi_reg_1017;
reg   [14:0] data_14_V_read28_phi_reg_1030;
reg   [14:0] data_15_V_read29_phi_reg_1043;
reg   [14:0] data_16_V_read30_phi_reg_1056;
reg   [14:0] data_17_V_read31_phi_reg_1069;
reg   [14:0] data_18_V_read32_phi_reg_1082;
reg   [14:0] data_19_V_read33_phi_reg_1095;
reg   [14:0] data_20_V_read34_phi_reg_1108;
reg   [14:0] data_21_V_read35_phi_reg_1121;
reg   [14:0] data_22_V_read36_phi_reg_1134;
reg   [14:0] data_23_V_read37_phi_reg_1147;
reg   [14:0] data_24_V_read38_phi_reg_1160;
reg   [14:0] data_25_V_read39_phi_reg_1173;
reg   [14:0] data_26_V_read40_phi_reg_1186;
reg   [14:0] data_27_V_read41_phi_reg_1199;
reg   [14:0] data_28_V_read42_phi_reg_1212;
reg   [14:0] data_29_V_read43_phi_reg_1225;
reg   [14:0] data_30_V_read44_phi_reg_1238;
reg   [14:0] data_31_V_read45_phi_reg_1251;
reg   [15:0] res_0_V_write_assign11_reg_1264;
reg   [15:0] res_1_V_write_assign9_reg_1278;
reg   [15:0] res_2_V_write_assign7_reg_1292;
reg   [15:0] res_3_V_write_assign5_reg_1306;
reg   [15:0] res_4_V_write_assign3_reg_1320;
wire   [3:0] w_index_fu_1339_p2;
reg   [3:0] w_index_reg_2466;
reg   [0:0] icmp_ln64_reg_2471;
reg   [0:0] icmp_ln64_reg_2471_pp0_iter1_reg;
reg   [0:0] icmp_ln64_reg_2471_pp0_iter2_reg;
reg   [0:0] icmp_ln64_reg_2471_pp0_iter3_reg;
reg   [0:0] icmp_ln64_reg_2471_pp0_iter4_reg;
wire   [14:0] phi_ln_fu_1355_p34;
reg   [14:0] phi_ln_reg_2475;
wire   [15:0] trunc_ln76_fu_1425_p1;
reg  signed [15:0] trunc_ln76_reg_2480;
wire   [14:0] phi_ln76_s_fu_1437_p34;
reg   [14:0] phi_ln76_s_reg_2485;
reg  signed [15:0] tmp_s_reg_2490;
wire   [14:0] phi_ln76_125_fu_1517_p34;
reg   [14:0] phi_ln76_125_reg_2495;
reg  signed [15:0] tmp_125_reg_2500;
wire   [14:0] phi_ln76_126_fu_1597_p34;
reg   [14:0] phi_ln76_126_reg_2505;
reg  signed [15:0] tmp_126_reg_2510;
wire   [14:0] phi_ln76_127_fu_1677_p34;
reg   [14:0] phi_ln76_127_reg_2515;
reg  signed [15:0] tmp_127_reg_2520;
wire   [14:0] phi_ln76_128_fu_1757_p34;
reg   [14:0] phi_ln76_128_reg_2525;
reg  signed [15:0] tmp_128_reg_2530;
wire   [14:0] phi_ln76_129_fu_1837_p34;
reg   [14:0] phi_ln76_129_reg_2535;
reg  signed [15:0] tmp_129_reg_2540;
wire   [14:0] phi_ln76_130_fu_1917_p34;
reg   [14:0] phi_ln76_130_reg_2545;
reg  signed [15:0] tmp_130_reg_2550;
wire   [14:0] phi_ln76_131_fu_1997_p34;
reg   [14:0] phi_ln76_131_reg_2555;
reg  signed [15:0] tmp_131_reg_2560;
wire   [14:0] phi_ln76_132_fu_2077_p34;
reg   [14:0] phi_ln76_132_reg_2565;
reg  signed [11:0] tmp_132_reg_2570;
wire  signed [25:0] grp_fu_2401_p2;
reg  signed [25:0] mul_ln1118_reg_2675;
wire  signed [25:0] grp_fu_2407_p2;
reg  signed [25:0] mul_ln1118_132_reg_2680;
wire  signed [25:0] grp_fu_2413_p2;
reg  signed [25:0] mul_ln1118_133_reg_2685;
wire  signed [25:0] grp_fu_2419_p2;
reg  signed [25:0] mul_ln1118_134_reg_2690;
wire  signed [25:0] grp_fu_2425_p2;
reg  signed [25:0] mul_ln1118_135_reg_2695;
wire  signed [25:0] grp_fu_2431_p2;
reg  signed [25:0] mul_ln1118_136_reg_2700;
wire  signed [25:0] grp_fu_2437_p2;
reg  signed [25:0] mul_ln1118_137_reg_2705;
wire  signed [25:0] grp_fu_2443_p2;
reg  signed [25:0] mul_ln1118_138_reg_2710;
wire  signed [25:0] grp_fu_2449_p2;
reg  signed [25:0] mul_ln1118_139_reg_2715;
wire  signed [25:0] grp_fu_2455_p2;
reg  signed [25:0] mul_ln1118_140_reg_2720;
wire   [15:0] acc_0_V_fu_2241_p2;
reg    ap_enable_reg_pp0_iter5;
wire   [15:0] acc_1_V_fu_2271_p2;
wire   [15:0] acc_2_V_fu_2301_p2;
wire   [15:0] acc_3_V_fu_2331_p2;
wire   [15:0] acc_4_V_fu_2361_p2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] ap_phi_mux_do_init_phi_fu_373_p6;
wire    ap_block_pp0_stage0;
reg   [14:0] ap_phi_mux_data_0_V_read14_rewind_phi_fu_389_p6;
reg   [14:0] ap_phi_mux_data_1_V_read15_rewind_phi_fu_403_p6;
reg   [14:0] ap_phi_mux_data_2_V_read16_rewind_phi_fu_417_p6;
reg   [14:0] ap_phi_mux_data_3_V_read17_rewind_phi_fu_431_p6;
reg   [14:0] ap_phi_mux_data_4_V_read18_rewind_phi_fu_445_p6;
reg   [14:0] ap_phi_mux_data_5_V_read19_rewind_phi_fu_459_p6;
reg   [14:0] ap_phi_mux_data_6_V_read20_rewind_phi_fu_473_p6;
reg   [14:0] ap_phi_mux_data_7_V_read21_rewind_phi_fu_487_p6;
reg   [14:0] ap_phi_mux_data_8_V_read22_rewind_phi_fu_501_p6;
reg   [14:0] ap_phi_mux_data_9_V_read23_rewind_phi_fu_515_p6;
reg   [14:0] ap_phi_mux_data_10_V_read24_rewind_phi_fu_529_p6;
reg   [14:0] ap_phi_mux_data_11_V_read25_rewind_phi_fu_543_p6;
reg   [14:0] ap_phi_mux_data_12_V_read26_rewind_phi_fu_557_p6;
reg   [14:0] ap_phi_mux_data_13_V_read27_rewind_phi_fu_571_p6;
reg   [14:0] ap_phi_mux_data_14_V_read28_rewind_phi_fu_585_p6;
reg   [14:0] ap_phi_mux_data_15_V_read29_rewind_phi_fu_599_p6;
reg   [14:0] ap_phi_mux_data_16_V_read30_rewind_phi_fu_613_p6;
reg   [14:0] ap_phi_mux_data_17_V_read31_rewind_phi_fu_627_p6;
reg   [14:0] ap_phi_mux_data_18_V_read32_rewind_phi_fu_641_p6;
reg   [14:0] ap_phi_mux_data_19_V_read33_rewind_phi_fu_655_p6;
reg   [14:0] ap_phi_mux_data_20_V_read34_rewind_phi_fu_669_p6;
reg   [14:0] ap_phi_mux_data_21_V_read35_rewind_phi_fu_683_p6;
reg   [14:0] ap_phi_mux_data_22_V_read36_rewind_phi_fu_697_p6;
reg   [14:0] ap_phi_mux_data_23_V_read37_rewind_phi_fu_711_p6;
reg   [14:0] ap_phi_mux_data_24_V_read38_rewind_phi_fu_725_p6;
reg   [14:0] ap_phi_mux_data_25_V_read39_rewind_phi_fu_739_p6;
reg   [14:0] ap_phi_mux_data_26_V_read40_rewind_phi_fu_753_p6;
reg   [14:0] ap_phi_mux_data_27_V_read41_rewind_phi_fu_767_p6;
reg   [14:0] ap_phi_mux_data_28_V_read42_rewind_phi_fu_781_p6;
reg   [14:0] ap_phi_mux_data_29_V_read43_rewind_phi_fu_795_p6;
reg   [14:0] ap_phi_mux_data_30_V_read44_rewind_phi_fu_809_p6;
reg   [14:0] ap_phi_mux_data_31_V_read45_rewind_phi_fu_823_p6;
reg   [3:0] ap_phi_mux_w_index13_phi_fu_837_p6;
wire   [14:0] ap_phi_reg_pp0_iter0_data_0_V_read14_phi_reg_848;
wire   [14:0] ap_phi_reg_pp0_iter0_data_1_V_read15_phi_reg_861;
wire   [14:0] ap_phi_reg_pp0_iter0_data_2_V_read16_phi_reg_874;
wire   [14:0] ap_phi_reg_pp0_iter0_data_3_V_read17_phi_reg_887;
wire   [14:0] ap_phi_reg_pp0_iter0_data_4_V_read18_phi_reg_900;
wire   [14:0] ap_phi_reg_pp0_iter0_data_5_V_read19_phi_reg_913;
wire   [14:0] ap_phi_reg_pp0_iter0_data_6_V_read20_phi_reg_926;
wire   [14:0] ap_phi_reg_pp0_iter0_data_7_V_read21_phi_reg_939;
wire   [14:0] ap_phi_reg_pp0_iter0_data_8_V_read22_phi_reg_952;
wire   [14:0] ap_phi_reg_pp0_iter0_data_9_V_read23_phi_reg_965;
wire   [14:0] ap_phi_reg_pp0_iter0_data_10_V_read24_phi_reg_978;
wire   [14:0] ap_phi_reg_pp0_iter0_data_11_V_read25_phi_reg_991;
wire   [14:0] ap_phi_reg_pp0_iter0_data_12_V_read26_phi_reg_1004;
wire   [14:0] ap_phi_reg_pp0_iter0_data_13_V_read27_phi_reg_1017;
wire   [14:0] ap_phi_reg_pp0_iter0_data_14_V_read28_phi_reg_1030;
wire   [14:0] ap_phi_reg_pp0_iter0_data_15_V_read29_phi_reg_1043;
wire   [14:0] ap_phi_reg_pp0_iter0_data_16_V_read30_phi_reg_1056;
wire   [14:0] ap_phi_reg_pp0_iter0_data_17_V_read31_phi_reg_1069;
wire   [14:0] ap_phi_reg_pp0_iter0_data_18_V_read32_phi_reg_1082;
wire   [14:0] ap_phi_reg_pp0_iter0_data_19_V_read33_phi_reg_1095;
wire   [14:0] ap_phi_reg_pp0_iter0_data_20_V_read34_phi_reg_1108;
wire   [14:0] ap_phi_reg_pp0_iter0_data_21_V_read35_phi_reg_1121;
wire   [14:0] ap_phi_reg_pp0_iter0_data_22_V_read36_phi_reg_1134;
wire   [14:0] ap_phi_reg_pp0_iter0_data_23_V_read37_phi_reg_1147;
wire   [14:0] ap_phi_reg_pp0_iter0_data_24_V_read38_phi_reg_1160;
wire   [14:0] ap_phi_reg_pp0_iter0_data_25_V_read39_phi_reg_1173;
wire   [14:0] ap_phi_reg_pp0_iter0_data_26_V_read40_phi_reg_1186;
wire   [14:0] ap_phi_reg_pp0_iter0_data_27_V_read41_phi_reg_1199;
wire   [14:0] ap_phi_reg_pp0_iter0_data_28_V_read42_phi_reg_1212;
wire   [14:0] ap_phi_reg_pp0_iter0_data_29_V_read43_phi_reg_1225;
wire   [14:0] ap_phi_reg_pp0_iter0_data_30_V_read44_phi_reg_1238;
wire   [14:0] ap_phi_reg_pp0_iter0_data_31_V_read45_phi_reg_1251;
wire   [63:0] zext_ln76_fu_1334_p1;
wire   [4:0] zext_ln64_fu_1351_p1;
wire   [4:0] xor_ln_fu_1429_p3;
wire   [15:0] trunc_ln708_s_fu_2226_p4;
wire   [15:0] trunc_ln_fu_2217_p4;
wire   [15:0] add_ln703_fu_2235_p2;
wire   [15:0] trunc_ln708_132_fu_2256_p4;
wire   [15:0] trunc_ln708_131_fu_2247_p4;
wire   [15:0] add_ln703_195_fu_2265_p2;
wire   [15:0] trunc_ln708_134_fu_2286_p4;
wire   [15:0] trunc_ln708_133_fu_2277_p4;
wire   [15:0] add_ln703_197_fu_2295_p2;
wire   [15:0] trunc_ln708_136_fu_2316_p4;
wire   [15:0] trunc_ln708_135_fu_2307_p4;
wire   [15:0] add_ln703_199_fu_2325_p2;
wire   [15:0] trunc_ln708_138_fu_2346_p4;
wire   [15:0] trunc_ln708_137_fu_2337_p4;
wire   [15:0] add_ln703_201_fu_2355_p2;
wire   [14:0] grp_fu_2401_p1;
wire   [14:0] grp_fu_2407_p1;
wire   [14:0] grp_fu_2413_p1;
wire   [14:0] grp_fu_2419_p1;
wire   [14:0] grp_fu_2425_p1;
wire   [14:0] grp_fu_2431_p1;
wire   [14:0] grp_fu_2437_p1;
wire   [14:0] grp_fu_2443_p1;
wire   [14:0] grp_fu_2449_p1;
wire   [14:0] grp_fu_2455_p0;
reg    grp_fu_2401_ce;
reg    grp_fu_2407_ce;
reg    grp_fu_2413_ce;
reg    grp_fu_2419_ce;
reg    grp_fu_2425_ce;
reg    grp_fu_2431_ce;
reg    grp_fu_2437_ce;
reg    grp_fu_2443_ce;
reg    grp_fu_2449_ce;
reg    grp_fu_2455_ce;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [15:0] ap_return_2_preg;
reg   [15:0] ap_return_3_preg;
reg   [15:0] ap_return_4_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [25:0] grp_fu_2401_p10;
wire   [25:0] grp_fu_2407_p10;
wire   [25:0] grp_fu_2413_p10;
wire   [25:0] grp_fu_2419_p10;
wire   [25:0] grp_fu_2425_p10;
wire   [25:0] grp_fu_2431_p10;
wire   [25:0] grp_fu_2437_p10;
wire   [25:0] grp_fu_2443_p10;
wire   [25:0] grp_fu_2449_p10;
wire   [25:0] grp_fu_2455_p00;
reg    ap_condition_385;
reg    ap_condition_46;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 16'd0;
#0 ap_return_3_preg = 16'd0;
#0 ap_return_4_preg = 16'd0;
end

dense_resource_ap_fixed_ap_fixed_16_6_5_3_0_config11_s_w1bkb #(
    .DataWidth( 156 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
w11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w11_V_address0),
    .ce0(w11_V_ce0),
    .q0(w11_V_q0)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U625(
    .din0(data_0_V_read14_phi_reg_848),
    .din1(data_1_V_read15_phi_reg_861),
    .din2(data_2_V_read16_phi_reg_874),
    .din3(data_3_V_read17_phi_reg_887),
    .din4(data_4_V_read18_phi_reg_900),
    .din5(data_5_V_read19_phi_reg_913),
    .din6(data_6_V_read20_phi_reg_926),
    .din7(data_7_V_read21_phi_reg_939),
    .din8(data_8_V_read22_phi_reg_952),
    .din9(data_9_V_read23_phi_reg_965),
    .din10(data_10_V_read24_phi_reg_978),
    .din11(data_11_V_read25_phi_reg_991),
    .din12(data_12_V_read26_phi_reg_1004),
    .din13(data_13_V_read27_phi_reg_1017),
    .din14(data_14_V_read28_phi_reg_1030),
    .din15(data_15_V_read29_phi_reg_1043),
    .din16(data_15_V_read29_phi_reg_1043),
    .din17(data_15_V_read29_phi_reg_1043),
    .din18(data_15_V_read29_phi_reg_1043),
    .din19(data_15_V_read29_phi_reg_1043),
    .din20(data_15_V_read29_phi_reg_1043),
    .din21(data_15_V_read29_phi_reg_1043),
    .din22(data_15_V_read29_phi_reg_1043),
    .din23(data_15_V_read29_phi_reg_1043),
    .din24(data_15_V_read29_phi_reg_1043),
    .din25(data_15_V_read29_phi_reg_1043),
    .din26(data_15_V_read29_phi_reg_1043),
    .din27(data_15_V_read29_phi_reg_1043),
    .din28(data_15_V_read29_phi_reg_1043),
    .din29(data_15_V_read29_phi_reg_1043),
    .din30(data_15_V_read29_phi_reg_1043),
    .din31(data_15_V_read29_phi_reg_1043),
    .din32(zext_ln64_fu_1351_p1),
    .dout(phi_ln_fu_1355_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U626(
    .din0(data_31_V_read45_phi_reg_1251),
    .din1(data_31_V_read45_phi_reg_1251),
    .din2(data_31_V_read45_phi_reg_1251),
    .din3(data_31_V_read45_phi_reg_1251),
    .din4(data_31_V_read45_phi_reg_1251),
    .din5(data_31_V_read45_phi_reg_1251),
    .din6(data_31_V_read45_phi_reg_1251),
    .din7(data_31_V_read45_phi_reg_1251),
    .din8(data_31_V_read45_phi_reg_1251),
    .din9(data_31_V_read45_phi_reg_1251),
    .din10(data_31_V_read45_phi_reg_1251),
    .din11(data_31_V_read45_phi_reg_1251),
    .din12(data_31_V_read45_phi_reg_1251),
    .din13(data_31_V_read45_phi_reg_1251),
    .din14(data_31_V_read45_phi_reg_1251),
    .din15(data_31_V_read45_phi_reg_1251),
    .din16(data_16_V_read30_phi_reg_1056),
    .din17(data_17_V_read31_phi_reg_1069),
    .din18(data_18_V_read32_phi_reg_1082),
    .din19(data_19_V_read33_phi_reg_1095),
    .din20(data_20_V_read34_phi_reg_1108),
    .din21(data_21_V_read35_phi_reg_1121),
    .din22(data_22_V_read36_phi_reg_1134),
    .din23(data_23_V_read37_phi_reg_1147),
    .din24(data_24_V_read38_phi_reg_1160),
    .din25(data_25_V_read39_phi_reg_1173),
    .din26(data_26_V_read40_phi_reg_1186),
    .din27(data_27_V_read41_phi_reg_1199),
    .din28(data_28_V_read42_phi_reg_1212),
    .din29(data_29_V_read43_phi_reg_1225),
    .din30(data_30_V_read44_phi_reg_1238),
    .din31(data_31_V_read45_phi_reg_1251),
    .din32(xor_ln_fu_1429_p3),
    .dout(phi_ln76_s_fu_1437_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U627(
    .din0(data_0_V_read14_phi_reg_848),
    .din1(data_1_V_read15_phi_reg_861),
    .din2(data_2_V_read16_phi_reg_874),
    .din3(data_3_V_read17_phi_reg_887),
    .din4(data_4_V_read18_phi_reg_900),
    .din5(data_5_V_read19_phi_reg_913),
    .din6(data_6_V_read20_phi_reg_926),
    .din7(data_7_V_read21_phi_reg_939),
    .din8(data_8_V_read22_phi_reg_952),
    .din9(data_9_V_read23_phi_reg_965),
    .din10(data_10_V_read24_phi_reg_978),
    .din11(data_11_V_read25_phi_reg_991),
    .din12(data_12_V_read26_phi_reg_1004),
    .din13(data_13_V_read27_phi_reg_1017),
    .din14(data_14_V_read28_phi_reg_1030),
    .din15(data_15_V_read29_phi_reg_1043),
    .din16(data_15_V_read29_phi_reg_1043),
    .din17(data_15_V_read29_phi_reg_1043),
    .din18(data_15_V_read29_phi_reg_1043),
    .din19(data_15_V_read29_phi_reg_1043),
    .din20(data_15_V_read29_phi_reg_1043),
    .din21(data_15_V_read29_phi_reg_1043),
    .din22(data_15_V_read29_phi_reg_1043),
    .din23(data_15_V_read29_phi_reg_1043),
    .din24(data_15_V_read29_phi_reg_1043),
    .din25(data_15_V_read29_phi_reg_1043),
    .din26(data_15_V_read29_phi_reg_1043),
    .din27(data_15_V_read29_phi_reg_1043),
    .din28(data_15_V_read29_phi_reg_1043),
    .din29(data_15_V_read29_phi_reg_1043),
    .din30(data_15_V_read29_phi_reg_1043),
    .din31(data_15_V_read29_phi_reg_1043),
    .din32(zext_ln64_fu_1351_p1),
    .dout(phi_ln76_125_fu_1517_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U628(
    .din0(data_31_V_read45_phi_reg_1251),
    .din1(data_31_V_read45_phi_reg_1251),
    .din2(data_31_V_read45_phi_reg_1251),
    .din3(data_31_V_read45_phi_reg_1251),
    .din4(data_31_V_read45_phi_reg_1251),
    .din5(data_31_V_read45_phi_reg_1251),
    .din6(data_31_V_read45_phi_reg_1251),
    .din7(data_31_V_read45_phi_reg_1251),
    .din8(data_31_V_read45_phi_reg_1251),
    .din9(data_31_V_read45_phi_reg_1251),
    .din10(data_31_V_read45_phi_reg_1251),
    .din11(data_31_V_read45_phi_reg_1251),
    .din12(data_31_V_read45_phi_reg_1251),
    .din13(data_31_V_read45_phi_reg_1251),
    .din14(data_31_V_read45_phi_reg_1251),
    .din15(data_31_V_read45_phi_reg_1251),
    .din16(data_16_V_read30_phi_reg_1056),
    .din17(data_17_V_read31_phi_reg_1069),
    .din18(data_18_V_read32_phi_reg_1082),
    .din19(data_19_V_read33_phi_reg_1095),
    .din20(data_20_V_read34_phi_reg_1108),
    .din21(data_21_V_read35_phi_reg_1121),
    .din22(data_22_V_read36_phi_reg_1134),
    .din23(data_23_V_read37_phi_reg_1147),
    .din24(data_24_V_read38_phi_reg_1160),
    .din25(data_25_V_read39_phi_reg_1173),
    .din26(data_26_V_read40_phi_reg_1186),
    .din27(data_27_V_read41_phi_reg_1199),
    .din28(data_28_V_read42_phi_reg_1212),
    .din29(data_29_V_read43_phi_reg_1225),
    .din30(data_30_V_read44_phi_reg_1238),
    .din31(data_31_V_read45_phi_reg_1251),
    .din32(xor_ln_fu_1429_p3),
    .dout(phi_ln76_126_fu_1597_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U629(
    .din0(data_0_V_read14_phi_reg_848),
    .din1(data_1_V_read15_phi_reg_861),
    .din2(data_2_V_read16_phi_reg_874),
    .din3(data_3_V_read17_phi_reg_887),
    .din4(data_4_V_read18_phi_reg_900),
    .din5(data_5_V_read19_phi_reg_913),
    .din6(data_6_V_read20_phi_reg_926),
    .din7(data_7_V_read21_phi_reg_939),
    .din8(data_8_V_read22_phi_reg_952),
    .din9(data_9_V_read23_phi_reg_965),
    .din10(data_10_V_read24_phi_reg_978),
    .din11(data_11_V_read25_phi_reg_991),
    .din12(data_12_V_read26_phi_reg_1004),
    .din13(data_13_V_read27_phi_reg_1017),
    .din14(data_14_V_read28_phi_reg_1030),
    .din15(data_15_V_read29_phi_reg_1043),
    .din16(data_15_V_read29_phi_reg_1043),
    .din17(data_15_V_read29_phi_reg_1043),
    .din18(data_15_V_read29_phi_reg_1043),
    .din19(data_15_V_read29_phi_reg_1043),
    .din20(data_15_V_read29_phi_reg_1043),
    .din21(data_15_V_read29_phi_reg_1043),
    .din22(data_15_V_read29_phi_reg_1043),
    .din23(data_15_V_read29_phi_reg_1043),
    .din24(data_15_V_read29_phi_reg_1043),
    .din25(data_15_V_read29_phi_reg_1043),
    .din26(data_15_V_read29_phi_reg_1043),
    .din27(data_15_V_read29_phi_reg_1043),
    .din28(data_15_V_read29_phi_reg_1043),
    .din29(data_15_V_read29_phi_reg_1043),
    .din30(data_15_V_read29_phi_reg_1043),
    .din31(data_15_V_read29_phi_reg_1043),
    .din32(zext_ln64_fu_1351_p1),
    .dout(phi_ln76_127_fu_1677_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U630(
    .din0(data_31_V_read45_phi_reg_1251),
    .din1(data_31_V_read45_phi_reg_1251),
    .din2(data_31_V_read45_phi_reg_1251),
    .din3(data_31_V_read45_phi_reg_1251),
    .din4(data_31_V_read45_phi_reg_1251),
    .din5(data_31_V_read45_phi_reg_1251),
    .din6(data_31_V_read45_phi_reg_1251),
    .din7(data_31_V_read45_phi_reg_1251),
    .din8(data_31_V_read45_phi_reg_1251),
    .din9(data_31_V_read45_phi_reg_1251),
    .din10(data_31_V_read45_phi_reg_1251),
    .din11(data_31_V_read45_phi_reg_1251),
    .din12(data_31_V_read45_phi_reg_1251),
    .din13(data_31_V_read45_phi_reg_1251),
    .din14(data_31_V_read45_phi_reg_1251),
    .din15(data_31_V_read45_phi_reg_1251),
    .din16(data_16_V_read30_phi_reg_1056),
    .din17(data_17_V_read31_phi_reg_1069),
    .din18(data_18_V_read32_phi_reg_1082),
    .din19(data_19_V_read33_phi_reg_1095),
    .din20(data_20_V_read34_phi_reg_1108),
    .din21(data_21_V_read35_phi_reg_1121),
    .din22(data_22_V_read36_phi_reg_1134),
    .din23(data_23_V_read37_phi_reg_1147),
    .din24(data_24_V_read38_phi_reg_1160),
    .din25(data_25_V_read39_phi_reg_1173),
    .din26(data_26_V_read40_phi_reg_1186),
    .din27(data_27_V_read41_phi_reg_1199),
    .din28(data_28_V_read42_phi_reg_1212),
    .din29(data_29_V_read43_phi_reg_1225),
    .din30(data_30_V_read44_phi_reg_1238),
    .din31(data_31_V_read45_phi_reg_1251),
    .din32(xor_ln_fu_1429_p3),
    .dout(phi_ln76_128_fu_1757_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U631(
    .din0(data_0_V_read14_phi_reg_848),
    .din1(data_1_V_read15_phi_reg_861),
    .din2(data_2_V_read16_phi_reg_874),
    .din3(data_3_V_read17_phi_reg_887),
    .din4(data_4_V_read18_phi_reg_900),
    .din5(data_5_V_read19_phi_reg_913),
    .din6(data_6_V_read20_phi_reg_926),
    .din7(data_7_V_read21_phi_reg_939),
    .din8(data_8_V_read22_phi_reg_952),
    .din9(data_9_V_read23_phi_reg_965),
    .din10(data_10_V_read24_phi_reg_978),
    .din11(data_11_V_read25_phi_reg_991),
    .din12(data_12_V_read26_phi_reg_1004),
    .din13(data_13_V_read27_phi_reg_1017),
    .din14(data_14_V_read28_phi_reg_1030),
    .din15(data_15_V_read29_phi_reg_1043),
    .din16(data_15_V_read29_phi_reg_1043),
    .din17(data_15_V_read29_phi_reg_1043),
    .din18(data_15_V_read29_phi_reg_1043),
    .din19(data_15_V_read29_phi_reg_1043),
    .din20(data_15_V_read29_phi_reg_1043),
    .din21(data_15_V_read29_phi_reg_1043),
    .din22(data_15_V_read29_phi_reg_1043),
    .din23(data_15_V_read29_phi_reg_1043),
    .din24(data_15_V_read29_phi_reg_1043),
    .din25(data_15_V_read29_phi_reg_1043),
    .din26(data_15_V_read29_phi_reg_1043),
    .din27(data_15_V_read29_phi_reg_1043),
    .din28(data_15_V_read29_phi_reg_1043),
    .din29(data_15_V_read29_phi_reg_1043),
    .din30(data_15_V_read29_phi_reg_1043),
    .din31(data_15_V_read29_phi_reg_1043),
    .din32(zext_ln64_fu_1351_p1),
    .dout(phi_ln76_129_fu_1837_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U632(
    .din0(data_31_V_read45_phi_reg_1251),
    .din1(data_31_V_read45_phi_reg_1251),
    .din2(data_31_V_read45_phi_reg_1251),
    .din3(data_31_V_read45_phi_reg_1251),
    .din4(data_31_V_read45_phi_reg_1251),
    .din5(data_31_V_read45_phi_reg_1251),
    .din6(data_31_V_read45_phi_reg_1251),
    .din7(data_31_V_read45_phi_reg_1251),
    .din8(data_31_V_read45_phi_reg_1251),
    .din9(data_31_V_read45_phi_reg_1251),
    .din10(data_31_V_read45_phi_reg_1251),
    .din11(data_31_V_read45_phi_reg_1251),
    .din12(data_31_V_read45_phi_reg_1251),
    .din13(data_31_V_read45_phi_reg_1251),
    .din14(data_31_V_read45_phi_reg_1251),
    .din15(data_31_V_read45_phi_reg_1251),
    .din16(data_16_V_read30_phi_reg_1056),
    .din17(data_17_V_read31_phi_reg_1069),
    .din18(data_18_V_read32_phi_reg_1082),
    .din19(data_19_V_read33_phi_reg_1095),
    .din20(data_20_V_read34_phi_reg_1108),
    .din21(data_21_V_read35_phi_reg_1121),
    .din22(data_22_V_read36_phi_reg_1134),
    .din23(data_23_V_read37_phi_reg_1147),
    .din24(data_24_V_read38_phi_reg_1160),
    .din25(data_25_V_read39_phi_reg_1173),
    .din26(data_26_V_read40_phi_reg_1186),
    .din27(data_27_V_read41_phi_reg_1199),
    .din28(data_28_V_read42_phi_reg_1212),
    .din29(data_29_V_read43_phi_reg_1225),
    .din30(data_30_V_read44_phi_reg_1238),
    .din31(data_31_V_read45_phi_reg_1251),
    .din32(xor_ln_fu_1429_p3),
    .dout(phi_ln76_130_fu_1917_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U633(
    .din0(data_0_V_read14_phi_reg_848),
    .din1(data_1_V_read15_phi_reg_861),
    .din2(data_2_V_read16_phi_reg_874),
    .din3(data_3_V_read17_phi_reg_887),
    .din4(data_4_V_read18_phi_reg_900),
    .din5(data_5_V_read19_phi_reg_913),
    .din6(data_6_V_read20_phi_reg_926),
    .din7(data_7_V_read21_phi_reg_939),
    .din8(data_8_V_read22_phi_reg_952),
    .din9(data_9_V_read23_phi_reg_965),
    .din10(data_10_V_read24_phi_reg_978),
    .din11(data_11_V_read25_phi_reg_991),
    .din12(data_12_V_read26_phi_reg_1004),
    .din13(data_13_V_read27_phi_reg_1017),
    .din14(data_14_V_read28_phi_reg_1030),
    .din15(data_15_V_read29_phi_reg_1043),
    .din16(data_15_V_read29_phi_reg_1043),
    .din17(data_15_V_read29_phi_reg_1043),
    .din18(data_15_V_read29_phi_reg_1043),
    .din19(data_15_V_read29_phi_reg_1043),
    .din20(data_15_V_read29_phi_reg_1043),
    .din21(data_15_V_read29_phi_reg_1043),
    .din22(data_15_V_read29_phi_reg_1043),
    .din23(data_15_V_read29_phi_reg_1043),
    .din24(data_15_V_read29_phi_reg_1043),
    .din25(data_15_V_read29_phi_reg_1043),
    .din26(data_15_V_read29_phi_reg_1043),
    .din27(data_15_V_read29_phi_reg_1043),
    .din28(data_15_V_read29_phi_reg_1043),
    .din29(data_15_V_read29_phi_reg_1043),
    .din30(data_15_V_read29_phi_reg_1043),
    .din31(data_15_V_read29_phi_reg_1043),
    .din32(zext_ln64_fu_1351_p1),
    .dout(phi_ln76_131_fu_1997_p34)
);

myproject_axi_mux_325_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 15 ),
    .din12_WIDTH( 15 ),
    .din13_WIDTH( 15 ),
    .din14_WIDTH( 15 ),
    .din15_WIDTH( 15 ),
    .din16_WIDTH( 15 ),
    .din17_WIDTH( 15 ),
    .din18_WIDTH( 15 ),
    .din19_WIDTH( 15 ),
    .din20_WIDTH( 15 ),
    .din21_WIDTH( 15 ),
    .din22_WIDTH( 15 ),
    .din23_WIDTH( 15 ),
    .din24_WIDTH( 15 ),
    .din25_WIDTH( 15 ),
    .din26_WIDTH( 15 ),
    .din27_WIDTH( 15 ),
    .din28_WIDTH( 15 ),
    .din29_WIDTH( 15 ),
    .din30_WIDTH( 15 ),
    .din31_WIDTH( 15 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
myproject_axi_mux_325_15_1_1_U634(
    .din0(data_31_V_read45_phi_reg_1251),
    .din1(data_31_V_read45_phi_reg_1251),
    .din2(data_31_V_read45_phi_reg_1251),
    .din3(data_31_V_read45_phi_reg_1251),
    .din4(data_31_V_read45_phi_reg_1251),
    .din5(data_31_V_read45_phi_reg_1251),
    .din6(data_31_V_read45_phi_reg_1251),
    .din7(data_31_V_read45_phi_reg_1251),
    .din8(data_31_V_read45_phi_reg_1251),
    .din9(data_31_V_read45_phi_reg_1251),
    .din10(data_31_V_read45_phi_reg_1251),
    .din11(data_31_V_read45_phi_reg_1251),
    .din12(data_31_V_read45_phi_reg_1251),
    .din13(data_31_V_read45_phi_reg_1251),
    .din14(data_31_V_read45_phi_reg_1251),
    .din15(data_31_V_read45_phi_reg_1251),
    .din16(data_16_V_read30_phi_reg_1056),
    .din17(data_17_V_read31_phi_reg_1069),
    .din18(data_18_V_read32_phi_reg_1082),
    .din19(data_19_V_read33_phi_reg_1095),
    .din20(data_20_V_read34_phi_reg_1108),
    .din21(data_21_V_read35_phi_reg_1121),
    .din22(data_22_V_read36_phi_reg_1134),
    .din23(data_23_V_read37_phi_reg_1147),
    .din24(data_24_V_read38_phi_reg_1160),
    .din25(data_25_V_read39_phi_reg_1173),
    .din26(data_26_V_read40_phi_reg_1186),
    .din27(data_27_V_read41_phi_reg_1199),
    .din28(data_28_V_read42_phi_reg_1212),
    .din29(data_29_V_read43_phi_reg_1225),
    .din30(data_30_V_read44_phi_reg_1238),
    .din31(data_31_V_read45_phi_reg_1251),
    .din32(xor_ln_fu_1429_p3),
    .dout(phi_ln76_132_fu_2077_p34)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U635(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln76_reg_2480),
    .din1(grp_fu_2401_p1),
    .ce(grp_fu_2401_ce),
    .dout(grp_fu_2401_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U636(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_reg_2490),
    .din1(grp_fu_2407_p1),
    .ce(grp_fu_2407_ce),
    .dout(grp_fu_2407_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U637(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_125_reg_2500),
    .din1(grp_fu_2413_p1),
    .ce(grp_fu_2413_ce),
    .dout(grp_fu_2413_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U638(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_126_reg_2510),
    .din1(grp_fu_2419_p1),
    .ce(grp_fu_2419_ce),
    .dout(grp_fu_2419_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U639(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_127_reg_2520),
    .din1(grp_fu_2425_p1),
    .ce(grp_fu_2425_ce),
    .dout(grp_fu_2425_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U640(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_128_reg_2530),
    .din1(grp_fu_2431_p1),
    .ce(grp_fu_2431_ce),
    .dout(grp_fu_2431_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U641(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_129_reg_2540),
    .din1(grp_fu_2437_p1),
    .ce(grp_fu_2437_ce),
    .dout(grp_fu_2437_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U642(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_130_reg_2550),
    .din1(grp_fu_2443_p1),
    .ce(grp_fu_2443_ce),
    .dout(grp_fu_2443_p2)
);

myproject_axi_mul_mul_16s_15ns_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_16s_15ns_26_3_1_U643(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_131_reg_2560),
    .din1(grp_fu_2449_p1),
    .ce(grp_fu_2449_ce),
    .dout(grp_fu_2449_p2)
);

myproject_axi_mul_mul_15ns_12s_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_axi_mul_mul_15ns_12s_26_3_1_U644(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2455_p0),
    .din1(tmp_132_reg_2570),
    .ce(grp_fu_2455_ce),
    .dout(grp_fu_2455_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_return_0_preg <= acc_0_V_fu_2241_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_return_1_preg <= acc_1_V_fu_2271_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_return_2_preg <= acc_2_V_fu_2301_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_return_3_preg <= acc_3_V_fu_2331_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
            ap_return_4_preg <= acc_4_V_fu_2361_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_0_V_read14_phi_reg_848 <= ap_phi_mux_data_0_V_read14_rewind_phi_fu_389_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_0_V_read14_phi_reg_848 <= data_0_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_0_V_read14_phi_reg_848 <= ap_phi_reg_pp0_iter0_data_0_V_read14_phi_reg_848;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_10_V_read24_phi_reg_978 <= ap_phi_mux_data_10_V_read24_rewind_phi_fu_529_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_10_V_read24_phi_reg_978 <= data_10_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_10_V_read24_phi_reg_978 <= ap_phi_reg_pp0_iter0_data_10_V_read24_phi_reg_978;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_11_V_read25_phi_reg_991 <= ap_phi_mux_data_11_V_read25_rewind_phi_fu_543_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_11_V_read25_phi_reg_991 <= data_11_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_11_V_read25_phi_reg_991 <= ap_phi_reg_pp0_iter0_data_11_V_read25_phi_reg_991;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_12_V_read26_phi_reg_1004 <= ap_phi_mux_data_12_V_read26_rewind_phi_fu_557_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_12_V_read26_phi_reg_1004 <= data_12_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_12_V_read26_phi_reg_1004 <= ap_phi_reg_pp0_iter0_data_12_V_read26_phi_reg_1004;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_13_V_read27_phi_reg_1017 <= ap_phi_mux_data_13_V_read27_rewind_phi_fu_571_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_13_V_read27_phi_reg_1017 <= data_13_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_13_V_read27_phi_reg_1017 <= ap_phi_reg_pp0_iter0_data_13_V_read27_phi_reg_1017;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_14_V_read28_phi_reg_1030 <= ap_phi_mux_data_14_V_read28_rewind_phi_fu_585_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_14_V_read28_phi_reg_1030 <= data_14_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_14_V_read28_phi_reg_1030 <= ap_phi_reg_pp0_iter0_data_14_V_read28_phi_reg_1030;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_15_V_read29_phi_reg_1043 <= ap_phi_mux_data_15_V_read29_rewind_phi_fu_599_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_15_V_read29_phi_reg_1043 <= data_15_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_15_V_read29_phi_reg_1043 <= ap_phi_reg_pp0_iter0_data_15_V_read29_phi_reg_1043;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_16_V_read30_phi_reg_1056 <= ap_phi_mux_data_16_V_read30_rewind_phi_fu_613_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_16_V_read30_phi_reg_1056 <= data_16_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_16_V_read30_phi_reg_1056 <= ap_phi_reg_pp0_iter0_data_16_V_read30_phi_reg_1056;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_17_V_read31_phi_reg_1069 <= ap_phi_mux_data_17_V_read31_rewind_phi_fu_627_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_17_V_read31_phi_reg_1069 <= data_17_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_17_V_read31_phi_reg_1069 <= ap_phi_reg_pp0_iter0_data_17_V_read31_phi_reg_1069;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_18_V_read32_phi_reg_1082 <= ap_phi_mux_data_18_V_read32_rewind_phi_fu_641_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_18_V_read32_phi_reg_1082 <= data_18_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_18_V_read32_phi_reg_1082 <= ap_phi_reg_pp0_iter0_data_18_V_read32_phi_reg_1082;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_19_V_read33_phi_reg_1095 <= ap_phi_mux_data_19_V_read33_rewind_phi_fu_655_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_19_V_read33_phi_reg_1095 <= data_19_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_19_V_read33_phi_reg_1095 <= ap_phi_reg_pp0_iter0_data_19_V_read33_phi_reg_1095;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_1_V_read15_phi_reg_861 <= ap_phi_mux_data_1_V_read15_rewind_phi_fu_403_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_1_V_read15_phi_reg_861 <= data_1_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_1_V_read15_phi_reg_861 <= ap_phi_reg_pp0_iter0_data_1_V_read15_phi_reg_861;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_20_V_read34_phi_reg_1108 <= ap_phi_mux_data_20_V_read34_rewind_phi_fu_669_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_20_V_read34_phi_reg_1108 <= data_20_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_20_V_read34_phi_reg_1108 <= ap_phi_reg_pp0_iter0_data_20_V_read34_phi_reg_1108;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_21_V_read35_phi_reg_1121 <= ap_phi_mux_data_21_V_read35_rewind_phi_fu_683_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_21_V_read35_phi_reg_1121 <= data_21_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_21_V_read35_phi_reg_1121 <= ap_phi_reg_pp0_iter0_data_21_V_read35_phi_reg_1121;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_22_V_read36_phi_reg_1134 <= ap_phi_mux_data_22_V_read36_rewind_phi_fu_697_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_22_V_read36_phi_reg_1134 <= data_22_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_22_V_read36_phi_reg_1134 <= ap_phi_reg_pp0_iter0_data_22_V_read36_phi_reg_1134;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_23_V_read37_phi_reg_1147 <= ap_phi_mux_data_23_V_read37_rewind_phi_fu_711_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_23_V_read37_phi_reg_1147 <= data_23_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_23_V_read37_phi_reg_1147 <= ap_phi_reg_pp0_iter0_data_23_V_read37_phi_reg_1147;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_24_V_read38_phi_reg_1160 <= ap_phi_mux_data_24_V_read38_rewind_phi_fu_725_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_24_V_read38_phi_reg_1160 <= data_24_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_24_V_read38_phi_reg_1160 <= ap_phi_reg_pp0_iter0_data_24_V_read38_phi_reg_1160;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_25_V_read39_phi_reg_1173 <= ap_phi_mux_data_25_V_read39_rewind_phi_fu_739_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_25_V_read39_phi_reg_1173 <= data_25_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_25_V_read39_phi_reg_1173 <= ap_phi_reg_pp0_iter0_data_25_V_read39_phi_reg_1173;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_26_V_read40_phi_reg_1186 <= ap_phi_mux_data_26_V_read40_rewind_phi_fu_753_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_26_V_read40_phi_reg_1186 <= data_26_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_26_V_read40_phi_reg_1186 <= ap_phi_reg_pp0_iter0_data_26_V_read40_phi_reg_1186;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_27_V_read41_phi_reg_1199 <= ap_phi_mux_data_27_V_read41_rewind_phi_fu_767_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_27_V_read41_phi_reg_1199 <= data_27_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_27_V_read41_phi_reg_1199 <= ap_phi_reg_pp0_iter0_data_27_V_read41_phi_reg_1199;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_28_V_read42_phi_reg_1212 <= ap_phi_mux_data_28_V_read42_rewind_phi_fu_781_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_28_V_read42_phi_reg_1212 <= data_28_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_28_V_read42_phi_reg_1212 <= ap_phi_reg_pp0_iter0_data_28_V_read42_phi_reg_1212;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_29_V_read43_phi_reg_1225 <= ap_phi_mux_data_29_V_read43_rewind_phi_fu_795_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_29_V_read43_phi_reg_1225 <= data_29_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_29_V_read43_phi_reg_1225 <= ap_phi_reg_pp0_iter0_data_29_V_read43_phi_reg_1225;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_2_V_read16_phi_reg_874 <= ap_phi_mux_data_2_V_read16_rewind_phi_fu_417_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_2_V_read16_phi_reg_874 <= data_2_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_2_V_read16_phi_reg_874 <= ap_phi_reg_pp0_iter0_data_2_V_read16_phi_reg_874;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_30_V_read44_phi_reg_1238 <= ap_phi_mux_data_30_V_read44_rewind_phi_fu_809_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_30_V_read44_phi_reg_1238 <= data_30_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_30_V_read44_phi_reg_1238 <= ap_phi_reg_pp0_iter0_data_30_V_read44_phi_reg_1238;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_31_V_read45_phi_reg_1251 <= ap_phi_mux_data_31_V_read45_rewind_phi_fu_823_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_31_V_read45_phi_reg_1251 <= data_31_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_31_V_read45_phi_reg_1251 <= ap_phi_reg_pp0_iter0_data_31_V_read45_phi_reg_1251;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_3_V_read17_phi_reg_887 <= ap_phi_mux_data_3_V_read17_rewind_phi_fu_431_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_3_V_read17_phi_reg_887 <= data_3_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_3_V_read17_phi_reg_887 <= ap_phi_reg_pp0_iter0_data_3_V_read17_phi_reg_887;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_4_V_read18_phi_reg_900 <= ap_phi_mux_data_4_V_read18_rewind_phi_fu_445_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_4_V_read18_phi_reg_900 <= data_4_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_4_V_read18_phi_reg_900 <= ap_phi_reg_pp0_iter0_data_4_V_read18_phi_reg_900;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_5_V_read19_phi_reg_913 <= ap_phi_mux_data_5_V_read19_rewind_phi_fu_459_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_5_V_read19_phi_reg_913 <= data_5_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_5_V_read19_phi_reg_913 <= ap_phi_reg_pp0_iter0_data_5_V_read19_phi_reg_913;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_6_V_read20_phi_reg_926 <= ap_phi_mux_data_6_V_read20_rewind_phi_fu_473_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_6_V_read20_phi_reg_926 <= data_6_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_6_V_read20_phi_reg_926 <= ap_phi_reg_pp0_iter0_data_6_V_read20_phi_reg_926;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_7_V_read21_phi_reg_939 <= ap_phi_mux_data_7_V_read21_rewind_phi_fu_487_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_7_V_read21_phi_reg_939 <= data_7_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_7_V_read21_phi_reg_939 <= ap_phi_reg_pp0_iter0_data_7_V_read21_phi_reg_939;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_8_V_read22_phi_reg_952 <= ap_phi_mux_data_8_V_read22_rewind_phi_fu_501_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_8_V_read22_phi_reg_952 <= data_8_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_8_V_read22_phi_reg_952 <= ap_phi_reg_pp0_iter0_data_8_V_read22_phi_reg_952;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_46)) begin
        if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd0)) begin
            data_9_V_read23_phi_reg_965 <= ap_phi_mux_data_9_V_read23_rewind_phi_fu_515_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_373_p6 == 1'd1)) begin
            data_9_V_read23_phi_reg_965 <= data_9_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_9_V_read23_phi_reg_965 <= ap_phi_reg_pp0_iter0_data_9_V_read23_phi_reg_965;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_369 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_369 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        res_0_V_write_assign11_reg_1264 <= acc_0_V_fu_2241_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_0_V_write_assign11_reg_1264 <= 16'd19;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        res_1_V_write_assign9_reg_1278 <= acc_1_V_fu_2271_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_1_V_write_assign9_reg_1278 <= 16'd38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        res_2_V_write_assign7_reg_1292 <= acc_2_V_fu_2301_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_2_V_write_assign7_reg_1292 <= 16'd75;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        res_3_V_write_assign5_reg_1306 <= acc_3_V_fu_2331_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_3_V_write_assign5_reg_1306 <= 16'd65480;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        res_4_V_write_assign3_reg_1320 <= acc_4_V_fu_2361_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_4_V_write_assign3_reg_1320 <= 16'd65420;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index13_reg_833 <= w_index_reg_2466;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index13_reg_833 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_0_V_read14_rewind_reg_385 <= data_0_V_read14_phi_reg_848;
        data_10_V_read24_rewind_reg_525 <= data_10_V_read24_phi_reg_978;
        data_11_V_read25_rewind_reg_539 <= data_11_V_read25_phi_reg_991;
        data_12_V_read26_rewind_reg_553 <= data_12_V_read26_phi_reg_1004;
        data_13_V_read27_rewind_reg_567 <= data_13_V_read27_phi_reg_1017;
        data_14_V_read28_rewind_reg_581 <= data_14_V_read28_phi_reg_1030;
        data_15_V_read29_rewind_reg_595 <= data_15_V_read29_phi_reg_1043;
        data_16_V_read30_rewind_reg_609 <= data_16_V_read30_phi_reg_1056;
        data_17_V_read31_rewind_reg_623 <= data_17_V_read31_phi_reg_1069;
        data_18_V_read32_rewind_reg_637 <= data_18_V_read32_phi_reg_1082;
        data_19_V_read33_rewind_reg_651 <= data_19_V_read33_phi_reg_1095;
        data_1_V_read15_rewind_reg_399 <= data_1_V_read15_phi_reg_861;
        data_20_V_read34_rewind_reg_665 <= data_20_V_read34_phi_reg_1108;
        data_21_V_read35_rewind_reg_679 <= data_21_V_read35_phi_reg_1121;
        data_22_V_read36_rewind_reg_693 <= data_22_V_read36_phi_reg_1134;
        data_23_V_read37_rewind_reg_707 <= data_23_V_read37_phi_reg_1147;
        data_24_V_read38_rewind_reg_721 <= data_24_V_read38_phi_reg_1160;
        data_25_V_read39_rewind_reg_735 <= data_25_V_read39_phi_reg_1173;
        data_26_V_read40_rewind_reg_749 <= data_26_V_read40_phi_reg_1186;
        data_27_V_read41_rewind_reg_763 <= data_27_V_read41_phi_reg_1199;
        data_28_V_read42_rewind_reg_777 <= data_28_V_read42_phi_reg_1212;
        data_29_V_read43_rewind_reg_791 <= data_29_V_read43_phi_reg_1225;
        data_2_V_read16_rewind_reg_413 <= data_2_V_read16_phi_reg_874;
        data_30_V_read44_rewind_reg_805 <= data_30_V_read44_phi_reg_1238;
        data_31_V_read45_rewind_reg_819 <= data_31_V_read45_phi_reg_1251;
        data_3_V_read17_rewind_reg_427 <= data_3_V_read17_phi_reg_887;
        data_4_V_read18_rewind_reg_441 <= data_4_V_read18_phi_reg_900;
        data_5_V_read19_rewind_reg_455 <= data_5_V_read19_phi_reg_913;
        data_6_V_read20_rewind_reg_469 <= data_6_V_read20_phi_reg_926;
        data_7_V_read21_rewind_reg_483 <= data_7_V_read21_phi_reg_939;
        data_8_V_read22_rewind_reg_497 <= data_8_V_read22_phi_reg_952;
        data_9_V_read23_rewind_reg_511 <= data_9_V_read23_phi_reg_965;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln64_reg_2471 <= icmp_ln64_fu_1345_p2;
        icmp_ln64_reg_2471_pp0_iter1_reg <= icmp_ln64_reg_2471;
        phi_ln76_125_reg_2495 <= phi_ln76_125_fu_1517_p34;
        phi_ln76_126_reg_2505 <= phi_ln76_126_fu_1597_p34;
        phi_ln76_127_reg_2515 <= phi_ln76_127_fu_1677_p34;
        phi_ln76_128_reg_2525 <= phi_ln76_128_fu_1757_p34;
        phi_ln76_129_reg_2535 <= phi_ln76_129_fu_1837_p34;
        phi_ln76_130_reg_2545 <= phi_ln76_130_fu_1917_p34;
        phi_ln76_131_reg_2555 <= phi_ln76_131_fu_1997_p34;
        phi_ln76_132_reg_2565 <= phi_ln76_132_fu_2077_p34;
        phi_ln76_s_reg_2485 <= phi_ln76_s_fu_1437_p34;
        phi_ln_reg_2475 <= phi_ln_fu_1355_p34;
        tmp_125_reg_2500 <= {{w11_V_q0[47:32]}};
        tmp_126_reg_2510 <= {{w11_V_q0[63:48]}};
        tmp_127_reg_2520 <= {{w11_V_q0[79:64]}};
        tmp_128_reg_2530 <= {{w11_V_q0[95:80]}};
        tmp_129_reg_2540 <= {{w11_V_q0[111:96]}};
        tmp_130_reg_2550 <= {{w11_V_q0[127:112]}};
        tmp_131_reg_2560 <= {{w11_V_q0[143:128]}};
        tmp_132_reg_2570 <= {{w11_V_q0[155:144]}};
        tmp_s_reg_2490 <= {{w11_V_q0[31:16]}};
        trunc_ln76_reg_2480 <= trunc_ln76_fu_1425_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln64_reg_2471_pp0_iter2_reg <= icmp_ln64_reg_2471_pp0_iter1_reg;
        icmp_ln64_reg_2471_pp0_iter3_reg <= icmp_ln64_reg_2471_pp0_iter2_reg;
        icmp_ln64_reg_2471_pp0_iter4_reg <= icmp_ln64_reg_2471_pp0_iter3_reg;
        mul_ln1118_132_reg_2680 <= grp_fu_2407_p2;
        mul_ln1118_133_reg_2685 <= grp_fu_2413_p2;
        mul_ln1118_134_reg_2690 <= grp_fu_2419_p2;
        mul_ln1118_135_reg_2695 <= grp_fu_2425_p2;
        mul_ln1118_136_reg_2700 <= grp_fu_2431_p2;
        mul_ln1118_137_reg_2705 <= grp_fu_2437_p2;
        mul_ln1118_138_reg_2710 <= grp_fu_2443_p2;
        mul_ln1118_139_reg_2715 <= grp_fu_2449_p2;
        mul_ln1118_140_reg_2720 <= grp_fu_2455_p2;
        mul_ln1118_reg_2675 <= grp_fu_2401_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_2466 <= w_index_fu_1339_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_0_V_read14_rewind_phi_fu_389_p6 = data_0_V_read14_phi_reg_848;
    end else begin
        ap_phi_mux_data_0_V_read14_rewind_phi_fu_389_p6 = data_0_V_read14_rewind_reg_385;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_10_V_read24_rewind_phi_fu_529_p6 = data_10_V_read24_phi_reg_978;
    end else begin
        ap_phi_mux_data_10_V_read24_rewind_phi_fu_529_p6 = data_10_V_read24_rewind_reg_525;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_11_V_read25_rewind_phi_fu_543_p6 = data_11_V_read25_phi_reg_991;
    end else begin
        ap_phi_mux_data_11_V_read25_rewind_phi_fu_543_p6 = data_11_V_read25_rewind_reg_539;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_12_V_read26_rewind_phi_fu_557_p6 = data_12_V_read26_phi_reg_1004;
    end else begin
        ap_phi_mux_data_12_V_read26_rewind_phi_fu_557_p6 = data_12_V_read26_rewind_reg_553;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_13_V_read27_rewind_phi_fu_571_p6 = data_13_V_read27_phi_reg_1017;
    end else begin
        ap_phi_mux_data_13_V_read27_rewind_phi_fu_571_p6 = data_13_V_read27_rewind_reg_567;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_14_V_read28_rewind_phi_fu_585_p6 = data_14_V_read28_phi_reg_1030;
    end else begin
        ap_phi_mux_data_14_V_read28_rewind_phi_fu_585_p6 = data_14_V_read28_rewind_reg_581;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_15_V_read29_rewind_phi_fu_599_p6 = data_15_V_read29_phi_reg_1043;
    end else begin
        ap_phi_mux_data_15_V_read29_rewind_phi_fu_599_p6 = data_15_V_read29_rewind_reg_595;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_16_V_read30_rewind_phi_fu_613_p6 = data_16_V_read30_phi_reg_1056;
    end else begin
        ap_phi_mux_data_16_V_read30_rewind_phi_fu_613_p6 = data_16_V_read30_rewind_reg_609;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_17_V_read31_rewind_phi_fu_627_p6 = data_17_V_read31_phi_reg_1069;
    end else begin
        ap_phi_mux_data_17_V_read31_rewind_phi_fu_627_p6 = data_17_V_read31_rewind_reg_623;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_18_V_read32_rewind_phi_fu_641_p6 = data_18_V_read32_phi_reg_1082;
    end else begin
        ap_phi_mux_data_18_V_read32_rewind_phi_fu_641_p6 = data_18_V_read32_rewind_reg_637;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_19_V_read33_rewind_phi_fu_655_p6 = data_19_V_read33_phi_reg_1095;
    end else begin
        ap_phi_mux_data_19_V_read33_rewind_phi_fu_655_p6 = data_19_V_read33_rewind_reg_651;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_1_V_read15_rewind_phi_fu_403_p6 = data_1_V_read15_phi_reg_861;
    end else begin
        ap_phi_mux_data_1_V_read15_rewind_phi_fu_403_p6 = data_1_V_read15_rewind_reg_399;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_20_V_read34_rewind_phi_fu_669_p6 = data_20_V_read34_phi_reg_1108;
    end else begin
        ap_phi_mux_data_20_V_read34_rewind_phi_fu_669_p6 = data_20_V_read34_rewind_reg_665;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_21_V_read35_rewind_phi_fu_683_p6 = data_21_V_read35_phi_reg_1121;
    end else begin
        ap_phi_mux_data_21_V_read35_rewind_phi_fu_683_p6 = data_21_V_read35_rewind_reg_679;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_22_V_read36_rewind_phi_fu_697_p6 = data_22_V_read36_phi_reg_1134;
    end else begin
        ap_phi_mux_data_22_V_read36_rewind_phi_fu_697_p6 = data_22_V_read36_rewind_reg_693;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_23_V_read37_rewind_phi_fu_711_p6 = data_23_V_read37_phi_reg_1147;
    end else begin
        ap_phi_mux_data_23_V_read37_rewind_phi_fu_711_p6 = data_23_V_read37_rewind_reg_707;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_24_V_read38_rewind_phi_fu_725_p6 = data_24_V_read38_phi_reg_1160;
    end else begin
        ap_phi_mux_data_24_V_read38_rewind_phi_fu_725_p6 = data_24_V_read38_rewind_reg_721;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_25_V_read39_rewind_phi_fu_739_p6 = data_25_V_read39_phi_reg_1173;
    end else begin
        ap_phi_mux_data_25_V_read39_rewind_phi_fu_739_p6 = data_25_V_read39_rewind_reg_735;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_26_V_read40_rewind_phi_fu_753_p6 = data_26_V_read40_phi_reg_1186;
    end else begin
        ap_phi_mux_data_26_V_read40_rewind_phi_fu_753_p6 = data_26_V_read40_rewind_reg_749;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_27_V_read41_rewind_phi_fu_767_p6 = data_27_V_read41_phi_reg_1199;
    end else begin
        ap_phi_mux_data_27_V_read41_rewind_phi_fu_767_p6 = data_27_V_read41_rewind_reg_763;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_28_V_read42_rewind_phi_fu_781_p6 = data_28_V_read42_phi_reg_1212;
    end else begin
        ap_phi_mux_data_28_V_read42_rewind_phi_fu_781_p6 = data_28_V_read42_rewind_reg_777;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_29_V_read43_rewind_phi_fu_795_p6 = data_29_V_read43_phi_reg_1225;
    end else begin
        ap_phi_mux_data_29_V_read43_rewind_phi_fu_795_p6 = data_29_V_read43_rewind_reg_791;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_2_V_read16_rewind_phi_fu_417_p6 = data_2_V_read16_phi_reg_874;
    end else begin
        ap_phi_mux_data_2_V_read16_rewind_phi_fu_417_p6 = data_2_V_read16_rewind_reg_413;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_30_V_read44_rewind_phi_fu_809_p6 = data_30_V_read44_phi_reg_1238;
    end else begin
        ap_phi_mux_data_30_V_read44_rewind_phi_fu_809_p6 = data_30_V_read44_rewind_reg_805;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_31_V_read45_rewind_phi_fu_823_p6 = data_31_V_read45_phi_reg_1251;
    end else begin
        ap_phi_mux_data_31_V_read45_rewind_phi_fu_823_p6 = data_31_V_read45_rewind_reg_819;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_3_V_read17_rewind_phi_fu_431_p6 = data_3_V_read17_phi_reg_887;
    end else begin
        ap_phi_mux_data_3_V_read17_rewind_phi_fu_431_p6 = data_3_V_read17_rewind_reg_427;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_4_V_read18_rewind_phi_fu_445_p6 = data_4_V_read18_phi_reg_900;
    end else begin
        ap_phi_mux_data_4_V_read18_rewind_phi_fu_445_p6 = data_4_V_read18_rewind_reg_441;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_5_V_read19_rewind_phi_fu_459_p6 = data_5_V_read19_phi_reg_913;
    end else begin
        ap_phi_mux_data_5_V_read19_rewind_phi_fu_459_p6 = data_5_V_read19_rewind_reg_455;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_6_V_read20_rewind_phi_fu_473_p6 = data_6_V_read20_phi_reg_926;
    end else begin
        ap_phi_mux_data_6_V_read20_rewind_phi_fu_473_p6 = data_6_V_read20_rewind_reg_469;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_7_V_read21_rewind_phi_fu_487_p6 = data_7_V_read21_phi_reg_939;
    end else begin
        ap_phi_mux_data_7_V_read21_rewind_phi_fu_487_p6 = data_7_V_read21_rewind_reg_483;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_8_V_read22_rewind_phi_fu_501_p6 = data_8_V_read22_phi_reg_952;
    end else begin
        ap_phi_mux_data_8_V_read22_rewind_phi_fu_501_p6 = data_8_V_read22_rewind_reg_497;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2471 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_9_V_read23_rewind_phi_fu_515_p6 = data_9_V_read23_phi_reg_965;
    end else begin
        ap_phi_mux_data_9_V_read23_rewind_phi_fu_515_p6 = data_9_V_read23_rewind_reg_511;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_385)) begin
        if ((icmp_ln64_reg_2471 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_373_p6 = 1'd1;
        end else if ((icmp_ln64_reg_2471 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_373_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_373_p6 = do_init_reg_369;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_373_p6 = do_init_reg_369;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_385)) begin
        if ((icmp_ln64_reg_2471 == 1'd1)) begin
            ap_phi_mux_w_index13_phi_fu_837_p6 = 4'd0;
        end else if ((icmp_ln64_reg_2471 == 1'd0)) begin
            ap_phi_mux_w_index13_phi_fu_837_p6 = w_index_reg_2466;
        end else begin
            ap_phi_mux_w_index13_phi_fu_837_p6 = w_index13_reg_833;
        end
    end else begin
        ap_phi_mux_w_index13_phi_fu_837_p6 = w_index13_reg_833;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_fu_1345_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_return_0 = acc_0_V_fu_2241_p2;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_return_1 = acc_1_V_fu_2271_p2;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_return_2 = acc_2_V_fu_2301_p2;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_return_3 = acc_3_V_fu_2331_p2;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln64_reg_2471_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_return_4 = acc_4_V_fu_2361_p2;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2401_ce = 1'b1;
    end else begin
        grp_fu_2401_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2407_ce = 1'b1;
    end else begin
        grp_fu_2407_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2413_ce = 1'b1;
    end else begin
        grp_fu_2413_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2419_ce = 1'b1;
    end else begin
        grp_fu_2419_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2425_ce = 1'b1;
    end else begin
        grp_fu_2425_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2431_ce = 1'b1;
    end else begin
        grp_fu_2431_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2437_ce = 1'b1;
    end else begin
        grp_fu_2437_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2443_ce = 1'b1;
    end else begin
        grp_fu_2443_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2449_ce = 1'b1;
    end else begin
        grp_fu_2449_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2455_ce = 1'b1;
    end else begin
        grp_fu_2455_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_V_ce0 = 1'b1;
    end else begin
        w11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_2241_p2 = (res_0_V_write_assign11_reg_1264 + add_ln703_fu_2235_p2);

assign acc_1_V_fu_2271_p2 = (res_1_V_write_assign9_reg_1278 + add_ln703_195_fu_2265_p2);

assign acc_2_V_fu_2301_p2 = (res_2_V_write_assign7_reg_1292 + add_ln703_197_fu_2295_p2);

assign acc_3_V_fu_2331_p2 = (res_3_V_write_assign5_reg_1306 + add_ln703_199_fu_2325_p2);

assign acc_4_V_fu_2361_p2 = (res_4_V_write_assign3_reg_1320 + add_ln703_201_fu_2355_p2);

assign add_ln703_195_fu_2265_p2 = (trunc_ln708_132_fu_2256_p4 + trunc_ln708_131_fu_2247_p4);

assign add_ln703_197_fu_2295_p2 = (trunc_ln708_134_fu_2286_p4 + trunc_ln708_133_fu_2277_p4);

assign add_ln703_199_fu_2325_p2 = (trunc_ln708_136_fu_2316_p4 + trunc_ln708_135_fu_2307_p4);

assign add_ln703_201_fu_2355_p2 = (trunc_ln708_138_fu_2346_p4 + trunc_ln708_137_fu_2337_p4);

assign add_ln703_fu_2235_p2 = (trunc_ln708_s_fu_2226_p4 + trunc_ln_fu_2217_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_385 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_46 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_data_0_V_read14_phi_reg_848 = 'bx;

assign ap_phi_reg_pp0_iter0_data_10_V_read24_phi_reg_978 = 'bx;

assign ap_phi_reg_pp0_iter0_data_11_V_read25_phi_reg_991 = 'bx;

assign ap_phi_reg_pp0_iter0_data_12_V_read26_phi_reg_1004 = 'bx;

assign ap_phi_reg_pp0_iter0_data_13_V_read27_phi_reg_1017 = 'bx;

assign ap_phi_reg_pp0_iter0_data_14_V_read28_phi_reg_1030 = 'bx;

assign ap_phi_reg_pp0_iter0_data_15_V_read29_phi_reg_1043 = 'bx;

assign ap_phi_reg_pp0_iter0_data_16_V_read30_phi_reg_1056 = 'bx;

assign ap_phi_reg_pp0_iter0_data_17_V_read31_phi_reg_1069 = 'bx;

assign ap_phi_reg_pp0_iter0_data_18_V_read32_phi_reg_1082 = 'bx;

assign ap_phi_reg_pp0_iter0_data_19_V_read33_phi_reg_1095 = 'bx;

assign ap_phi_reg_pp0_iter0_data_1_V_read15_phi_reg_861 = 'bx;

assign ap_phi_reg_pp0_iter0_data_20_V_read34_phi_reg_1108 = 'bx;

assign ap_phi_reg_pp0_iter0_data_21_V_read35_phi_reg_1121 = 'bx;

assign ap_phi_reg_pp0_iter0_data_22_V_read36_phi_reg_1134 = 'bx;

assign ap_phi_reg_pp0_iter0_data_23_V_read37_phi_reg_1147 = 'bx;

assign ap_phi_reg_pp0_iter0_data_24_V_read38_phi_reg_1160 = 'bx;

assign ap_phi_reg_pp0_iter0_data_25_V_read39_phi_reg_1173 = 'bx;

assign ap_phi_reg_pp0_iter0_data_26_V_read40_phi_reg_1186 = 'bx;

assign ap_phi_reg_pp0_iter0_data_27_V_read41_phi_reg_1199 = 'bx;

assign ap_phi_reg_pp0_iter0_data_28_V_read42_phi_reg_1212 = 'bx;

assign ap_phi_reg_pp0_iter0_data_29_V_read43_phi_reg_1225 = 'bx;

assign ap_phi_reg_pp0_iter0_data_2_V_read16_phi_reg_874 = 'bx;

assign ap_phi_reg_pp0_iter0_data_30_V_read44_phi_reg_1238 = 'bx;

assign ap_phi_reg_pp0_iter0_data_31_V_read45_phi_reg_1251 = 'bx;

assign ap_phi_reg_pp0_iter0_data_3_V_read17_phi_reg_887 = 'bx;

assign ap_phi_reg_pp0_iter0_data_4_V_read18_phi_reg_900 = 'bx;

assign ap_phi_reg_pp0_iter0_data_5_V_read19_phi_reg_913 = 'bx;

assign ap_phi_reg_pp0_iter0_data_6_V_read20_phi_reg_926 = 'bx;

assign ap_phi_reg_pp0_iter0_data_7_V_read21_phi_reg_939 = 'bx;

assign ap_phi_reg_pp0_iter0_data_8_V_read22_phi_reg_952 = 'bx;

assign ap_phi_reg_pp0_iter0_data_9_V_read23_phi_reg_965 = 'bx;

assign grp_fu_2401_p1 = grp_fu_2401_p10;

assign grp_fu_2401_p10 = phi_ln_reg_2475;

assign grp_fu_2407_p1 = grp_fu_2407_p10;

assign grp_fu_2407_p10 = phi_ln76_s_reg_2485;

assign grp_fu_2413_p1 = grp_fu_2413_p10;

assign grp_fu_2413_p10 = phi_ln76_125_reg_2495;

assign grp_fu_2419_p1 = grp_fu_2419_p10;

assign grp_fu_2419_p10 = phi_ln76_126_reg_2505;

assign grp_fu_2425_p1 = grp_fu_2425_p10;

assign grp_fu_2425_p10 = phi_ln76_127_reg_2515;

assign grp_fu_2431_p1 = grp_fu_2431_p10;

assign grp_fu_2431_p10 = phi_ln76_128_reg_2525;

assign grp_fu_2437_p1 = grp_fu_2437_p10;

assign grp_fu_2437_p10 = phi_ln76_129_reg_2535;

assign grp_fu_2443_p1 = grp_fu_2443_p10;

assign grp_fu_2443_p10 = phi_ln76_130_reg_2545;

assign grp_fu_2449_p1 = grp_fu_2449_p10;

assign grp_fu_2449_p10 = phi_ln76_131_reg_2555;

assign grp_fu_2455_p0 = grp_fu_2455_p00;

assign grp_fu_2455_p00 = phi_ln76_132_reg_2565;

assign icmp_ln64_fu_1345_p2 = ((ap_phi_mux_w_index13_phi_fu_837_p6 == 4'd15) ? 1'b1 : 1'b0);

assign trunc_ln708_131_fu_2247_p4 = {{mul_ln1118_133_reg_2685[25:10]}};

assign trunc_ln708_132_fu_2256_p4 = {{mul_ln1118_134_reg_2690[25:10]}};

assign trunc_ln708_133_fu_2277_p4 = {{mul_ln1118_135_reg_2695[25:10]}};

assign trunc_ln708_134_fu_2286_p4 = {{mul_ln1118_136_reg_2700[25:10]}};

assign trunc_ln708_135_fu_2307_p4 = {{mul_ln1118_137_reg_2705[25:10]}};

assign trunc_ln708_136_fu_2316_p4 = {{mul_ln1118_138_reg_2710[25:10]}};

assign trunc_ln708_137_fu_2337_p4 = {{mul_ln1118_139_reg_2715[25:10]}};

assign trunc_ln708_138_fu_2346_p4 = {{mul_ln1118_140_reg_2720[25:10]}};

assign trunc_ln708_s_fu_2226_p4 = {{mul_ln1118_132_reg_2680[25:10]}};

assign trunc_ln76_fu_1425_p1 = w11_V_q0[15:0];

assign trunc_ln_fu_2217_p4 = {{mul_ln1118_reg_2675[25:10]}};

assign w11_V_address0 = zext_ln76_fu_1334_p1;

assign w_index_fu_1339_p2 = (4'd1 + ap_phi_mux_w_index13_phi_fu_837_p6);

assign xor_ln_fu_1429_p3 = {{1'd1}, {w_index13_reg_833}};

assign zext_ln64_fu_1351_p1 = w_index13_reg_833;

assign zext_ln76_fu_1334_p1 = ap_phi_mux_w_index13_phi_fu_837_p6;

endmodule //dense_resource_ap_fixed_ap_fixed_16_6_5_3_0_config11_s
