-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_2d_cl_array_array_ap_fixed_16u_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_V_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_V_empty_n : IN STD_LOGIC;
    data_V_data_V_read : OUT STD_LOGIC;
    res_V_data_0_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_0_V_full_n : IN STD_LOGIC;
    res_V_data_0_V_write : OUT STD_LOGIC;
    res_V_data_1_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_1_V_full_n : IN STD_LOGIC;
    res_V_data_1_V_write : OUT STD_LOGIC;
    res_V_data_2_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_2_V_full_n : IN STD_LOGIC;
    res_V_data_2_V_write : OUT STD_LOGIC;
    res_V_data_3_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_3_V_full_n : IN STD_LOGIC;
    res_V_data_3_V_write : OUT STD_LOGIC;
    res_V_data_4_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_4_V_full_n : IN STD_LOGIC;
    res_V_data_4_V_write : OUT STD_LOGIC;
    res_V_data_5_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_5_V_full_n : IN STD_LOGIC;
    res_V_data_5_V_write : OUT STD_LOGIC;
    res_V_data_6_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_6_V_full_n : IN STD_LOGIC;
    res_V_data_6_V_write : OUT STD_LOGIC;
    res_V_data_7_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_7_V_full_n : IN STD_LOGIC;
    res_V_data_7_V_write : OUT STD_LOGIC;
    res_V_data_8_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_8_V_full_n : IN STD_LOGIC;
    res_V_data_8_V_write : OUT STD_LOGIC;
    res_V_data_9_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_9_V_full_n : IN STD_LOGIC;
    res_V_data_9_V_write : OUT STD_LOGIC;
    res_V_data_10_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_10_V_full_n : IN STD_LOGIC;
    res_V_data_10_V_write : OUT STD_LOGIC;
    res_V_data_11_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_11_V_full_n : IN STD_LOGIC;
    res_V_data_11_V_write : OUT STD_LOGIC;
    res_V_data_12_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_12_V_full_n : IN STD_LOGIC;
    res_V_data_12_V_write : OUT STD_LOGIC;
    res_V_data_13_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_13_V_full_n : IN STD_LOGIC;
    res_V_data_13_V_write : OUT STD_LOGIC;
    res_V_data_14_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_14_V_full_n : IN STD_LOGIC;
    res_V_data_14_V_write : OUT STD_LOGIC;
    res_V_data_15_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    res_V_data_15_V_full_n : IN STD_LOGIC;
    res_V_data_15_V_write : OUT STD_LOGIC );
end;


architecture behav of conv_2d_cl_array_array_ap_fixed_16u_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_3FE : STD_LOGIC_VECTOR (9 downto 0) := "1111111110";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_1FA : STD_LOGIC_VECTOR (8 downto 0) := "111111010";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv9_1FE : STD_LOGIC_VECTOR (8 downto 0) := "111111110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal pX_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sX_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal kernel_data_V_1_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal kernel_data_V_1_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal kernel_data_V_1_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal kernel_data_V_1_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal kernel_data_V_1_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal kernel_data_V_1_8 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal data_V_data_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal res_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln78_reg_988 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln272_2_reg_1041 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_V_data_1_V_blk_n : STD_LOGIC;
    signal res_V_data_2_V_blk_n : STD_LOGIC;
    signal res_V_data_3_V_blk_n : STD_LOGIC;
    signal res_V_data_4_V_blk_n : STD_LOGIC;
    signal res_V_data_5_V_blk_n : STD_LOGIC;
    signal res_V_data_6_V_blk_n : STD_LOGIC;
    signal res_V_data_7_V_blk_n : STD_LOGIC;
    signal res_V_data_8_V_blk_n : STD_LOGIC;
    signal res_V_data_9_V_blk_n : STD_LOGIC;
    signal res_V_data_10_V_blk_n : STD_LOGIC;
    signal res_V_data_11_V_blk_n : STD_LOGIC;
    signal res_V_data_12_V_blk_n : STD_LOGIC;
    signal res_V_data_13_V_blk_n : STD_LOGIC;
    signal res_V_data_14_V_blk_n : STD_LOGIC;
    signal res_V_data_15_V_blk_n : STD_LOGIC;
    signal icmp_ln78_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln78_fu_263_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln78_reg_992 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_data_0_V_reg_997 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_data_V_1_6_ret_reg_1002 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal kernel_data_V_1_3_ret_reg_1008 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_data_V_1_1_ret_reg_1014 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_data_V_1_5_ret_reg_1021 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_data_V_1_7_ret_reg_1029 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_data_V_1_8_ret_reg_1035 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln272_2_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_reg_1045 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln708_s_reg_1050 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_46_reg_1055 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln293_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln293_reg_1060 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln308_fu_503_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln308_reg_1064 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln297_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln297_reg_1069 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln303_fu_547_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln303_reg_1073 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln708_239_reg_1078 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_45_reg_1083 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_47_reg_1088 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln708_243_reg_1093 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_48_reg_1098 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln708_245_reg_1103 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln708_4_reg_1108 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln708_246_reg_1114 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln703_200_fu_817_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln703_200_reg_1119 : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_1_V_fu_833_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_1_V_reg_1124 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln703_213_fu_839_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln703_213_reg_1129 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_start : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_done : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_idle : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_ready : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_4 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_5 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_6 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_7 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_8 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_reg_220 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal io_acc_block_signal_op173 : STD_LOGIC;
    signal ap_predicate_op173_write_state6 : BOOLEAN;
    signal ap_block_state6 : BOOLEAN;
    signal storemerge_i_i_reg_231 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln306_fu_485_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln301_fu_529_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_4_V_fu_871_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_170_fu_395_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_171_fu_415_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln272_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln272_1_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln272_4_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln272_5_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln272_1_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln272_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln308_fu_497_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln303_fu_541_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_567_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1118_1_fu_574_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_fu_564_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1118_fu_578_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_584_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln1118_fu_598_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1118_fu_604_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1116_fu_561_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln1118_1_fu_608_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_1_fu_627_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1118_3_fu_634_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_2_fu_624_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1118_1_fu_638_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln708_1_fu_657_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln1118_2_fu_673_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1118_5_fu_680_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_4_fu_670_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1118_2_fu_684_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln708_2_fu_700_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln1118_2_fu_713_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln708_3_fu_738_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln1118_3_fu_754_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1118_7_fu_761_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_6_fu_751_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1118_3_fu_765_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1118_4_fu_790_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1118_9_fu_797_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln1118_3_fu_801_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln708_2_fu_594_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln708_4_fu_654_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln703_203_fu_823_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln708_5_fu_666_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln703_1_fu_829_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln708_7_fu_709_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln708_9_fu_747_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln708_1_fu_850_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_9_V_fu_882_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln703_fu_893_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln708_fu_856_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln708_3_fu_859_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_2_V_fu_903_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln708_6_fu_862_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_11_V_fu_918_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln708_8_fu_868_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_data_0_V_4_fu_929_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln703_4_fu_940_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln708_fu_853_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal acc_12_V_fu_950_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln703_140_fu_879_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_8_V_fu_960_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1118_8_fu_876_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln708_1_fu_865_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_14_V_fu_971_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);

    component shift_line_buffer_array_ap_ufixed_1u_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_elem_data_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_window_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_window_2_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_window_4_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_window_5_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_window_7_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_window_8_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242 : component shift_line_buffer_array_ap_ufixed_1u_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_start,
        ap_done => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_done,
        ap_idle => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_idle,
        ap_ready => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_ready,
        in_elem_data_V_read => tmp_data_0_V_reg_997,
        kernel_window_1_V_read => kernel_data_V_1_1,
        kernel_window_2_V_read => kernel_data_V_1_2,
        kernel_window_4_V_read => kernel_data_V_1_4,
        kernel_window_5_V_read => kernel_data_V_1_5,
        kernel_window_7_V_read => kernel_data_V_1_7,
        kernel_window_8_V_read => kernel_data_V_1_8,
        ap_return_0 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_0,
        ap_return_1 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_1,
        ap_return_2 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_2,
        ap_return_3 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_3,
        ap_return_4 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_4,
        ap_return_5 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_5,
        ap_return_6 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_6,
        ap_return_7 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_7,
        ap_return_8 => call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_8,
        ap_ce => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
                indvar_flatten_reg_220 <= add_ln78_reg_992;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_220 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    pX_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                if ((icmp_ln293_fu_479_p2 = ap_const_lv1_1)) then 
                    pX_2 <= ap_const_lv32_0;
                elsif ((icmp_ln293_fu_479_p2 = ap_const_lv1_0)) then 
                    pX_2 <= add_ln306_fu_485_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln293_fu_479_p2 = ap_const_lv1_1))) then
                if ((icmp_ln297_fu_523_p2 = ap_const_lv1_1)) then 
                    pY_2 <= ap_const_lv32_0;
                elsif ((icmp_ln297_fu_523_p2 = ap_const_lv1_0)) then 
                    pY_2 <= add_ln301_fu_529_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln293_reg_1060 = ap_const_lv1_0) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
                sX_2 <= select_ln308_reg_1064;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln293_fu_479_p2 = ap_const_lv1_1))) then 
                sX_2 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    storemerge_i_i_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln297_fu_523_p2 = ap_const_lv1_1) and (icmp_ln293_fu_479_p2 = ap_const_lv1_1))) then 
                storemerge_i_i_reg_231 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln293_reg_1060 = ap_const_lv1_1) and (icmp_ln297_reg_1069 = ap_const_lv1_0) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
                storemerge_i_i_reg_231 <= select_ln303_reg_1073;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then
                acc_1_V_reg_1124 <= acc_1_V_fu_833_p2;
                add_ln703_200_reg_1119 <= add_ln703_200_fu_817_p2;
                add_ln703_213_reg_1129 <= add_ln703_213_fu_839_p2;
                lshr_ln708_4_reg_1108 <= kernel_data_V_1_8_ret_reg_1035(7 downto 1);
                tmp_45_reg_1083 <= add_ln1118_1_fu_638_p2(10 downto 3);
                tmp_47_reg_1088 <= add_ln1118_2_fu_684_p2(10 downto 3);
                tmp_48_reg_1098 <= kernel_data_V_1_6_ret_reg_1002(7 downto 3);
                trunc_ln708_239_reg_1078 <= sub_ln1118_1_fu_608_p2(11 downto 3);
                trunc_ln708_243_reg_1093 <= sub_ln1118_2_fu_713_p2(10 downto 3);
                trunc_ln708_245_reg_1103 <= add_ln1118_3_fu_765_p2(10 downto 3);
                trunc_ln708_246_reg_1114 <= sub_ln1118_3_fu_801_p2(10 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln78_reg_992 <= add_ln78_fu_263_p2;
                icmp_ln78_reg_988 <= icmp_ln78_fu_257_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                and_ln272_2_reg_1041 <= and_ln272_2_fu_443_p2;
                icmp_ln293_reg_1060 <= icmp_ln293_fu_479_p2;
                kernel_data_V_1_1 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_3;
                kernel_data_V_1_1_ret_reg_1014 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_3;
                kernel_data_V_1_2 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_4;
                kernel_data_V_1_3_ret_reg_1008 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_1;
                kernel_data_V_1_4 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_5;
                kernel_data_V_1_5 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_6;
                kernel_data_V_1_5_ret_reg_1021 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_6;
                kernel_data_V_1_6_ret_reg_1002 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_2;
                kernel_data_V_1_7 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_7;
                kernel_data_V_1_7_ret_reg_1029 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_7;
                kernel_data_V_1_8 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_8;
                kernel_data_V_1_8_ret_reg_1035 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln293_fu_479_p2 = ap_const_lv1_1))) then
                icmp_ln297_reg_1069 <= icmp_ln297_fu_523_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln272_2_fu_443_p2))) then
                lshr_ln708_s_reg_1050 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_4(7 downto 1);
                lshr_ln_reg_1045 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_0(7 downto 1);
                tmp_46_reg_1055 <= call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_return_5(7 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln293_reg_1060 = ap_const_lv1_1) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then
                sY_2 <= storemerge_i_i_reg_231;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln293_fu_479_p2 = ap_const_lv1_1) and (icmp_ln297_fu_523_p2 = ap_const_lv1_0))) then
                select_ln303_reg_1073 <= select_ln303_fu_547_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln293_fu_479_p2 = ap_const_lv1_0))) then
                select_ln308_reg_1064 <= select_ln308_fu_503_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((data_V_data_V_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_0_V_reg_997 <= data_V_data_V_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, data_V_data_V_empty_n, ap_CS_fsm_state3, ap_CS_fsm_state6, icmp_ln78_fu_257_p2, ap_CS_fsm_state2, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln78_fu_257_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state3 => 
                if (((data_V_data_V_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    acc_11_V_fu_918_p2 <= std_logic_vector(unsigned(zext_ln708_6_fu_862_p1) + unsigned(ap_const_lv9_1FF));
    acc_12_V_fu_950_p2 <= std_logic_vector(unsigned(trunc_ln708_245_reg_1103) + unsigned(ap_const_lv8_2));
    acc_14_V_fu_971_p2 <= std_logic_vector(unsigned(zext_ln1118_8_fu_876_p1) + unsigned(sext_ln708_1_fu_865_p1));
    acc_1_V_fu_833_p2 <= std_logic_vector(unsigned(zext_ln708_5_fu_666_p1) + unsigned(zext_ln703_1_fu_829_p1));
    acc_2_V_fu_903_p2 <= std_logic_vector(unsigned(zext_ln708_3_fu_859_p1) + unsigned(ap_const_lv9_1FF));
    acc_4_V_fu_871_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln708_4_reg_1108),10));
    acc_8_V_fu_960_p2 <= std_logic_vector(signed(sext_ln703_140_fu_879_p1) + signed(ap_const_lv9_1FE));
    acc_9_V_fu_882_p2 <= std_logic_vector(unsigned(zext_ln708_1_fu_850_p1) + unsigned(ap_const_lv8_1));
    add_ln1118_1_fu_638_p2 <= std_logic_vector(unsigned(zext_ln1118_3_fu_634_p1) + unsigned(zext_ln1118_2_fu_624_p1));
    add_ln1118_2_fu_684_p2 <= std_logic_vector(unsigned(zext_ln1118_5_fu_680_p1) + unsigned(zext_ln1118_4_fu_670_p1));
    add_ln1118_3_fu_765_p2 <= std_logic_vector(unsigned(zext_ln1118_7_fu_761_p1) + unsigned(zext_ln1118_6_fu_751_p1));
    add_ln1118_fu_578_p2 <= std_logic_vector(unsigned(zext_ln1118_1_fu_574_p1) + unsigned(zext_ln1118_fu_564_p1));
    add_ln301_fu_529_p2 <= std_logic_vector(unsigned(pY_2) + unsigned(ap_const_lv32_1));
    add_ln303_fu_541_p2 <= std_logic_vector(unsigned(sY_2) + unsigned(ap_const_lv32_1));
    add_ln306_fu_485_p2 <= std_logic_vector(unsigned(pX_2) + unsigned(ap_const_lv32_1));
    add_ln308_fu_497_p2 <= std_logic_vector(unsigned(sX_2) + unsigned(ap_const_lv32_1));
    add_ln703_200_fu_817_p2 <= std_logic_vector(unsigned(zext_ln708_2_fu_594_p1) + unsigned(ap_const_lv9_1FA));
    add_ln703_203_fu_823_p2 <= std_logic_vector(unsigned(zext_ln708_4_fu_654_p1) + unsigned(ap_const_lv6_2));
    add_ln703_213_fu_839_p2 <= std_logic_vector(unsigned(zext_ln708_7_fu_709_p1) + unsigned(zext_ln708_9_fu_747_p1));
    add_ln78_fu_263_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_220) + unsigned(ap_const_lv10_1));
    and_ln272_1_fu_437_p2 <= (icmp_ln272_5_fu_425_p2 and icmp_ln272_4_fu_405_p2);
    and_ln272_2_fu_443_p2 <= (and_ln272_fu_431_p2 and and_ln272_1_fu_437_p2);
    and_ln272_fu_431_p2 <= (icmp_ln272_fu_375_p2 and icmp_ln272_1_fu_385_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state6_assign_proc : process(io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
                ap_block_state6 <= ((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op173_write_state6_assign_proc : process(icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
                ap_predicate_op173_write_state6 <= ((ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;

    call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_start_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_start <= ap_const_logic_1;
        else 
            call_ret_shift_line_buffer_array_ap_ufixed_1u_config2_s_fu_242_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_V_blk_n_assign_proc : process(data_V_data_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_V_data_V_blk_n <= data_V_data_V_empty_n;
        else 
            data_V_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_V_read_assign_proc : process(data_V_data_V_empty_n, ap_CS_fsm_state3)
    begin
        if (((data_V_data_V_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_V_data_V_read <= ap_const_logic_1;
        else 
            data_V_data_V_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln272_1_fu_385_p2 <= "1" when (sY_2 = ap_const_lv32_2) else "0";
    icmp_ln272_4_fu_405_p2 <= "1" when (signed(tmp_170_fu_395_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln272_5_fu_425_p2 <= "1" when (signed(tmp_171_fu_415_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln272_fu_375_p2 <= "1" when (sX_2 = ap_const_lv32_2) else "0";
    icmp_ln293_fu_479_p2 <= "1" when (pX_2 = ap_const_lv32_1B) else "0";
    icmp_ln297_fu_523_p2 <= "1" when (pY_2 = ap_const_lv32_1B) else "0";
    icmp_ln78_fu_257_p2 <= "1" when (indvar_flatten_reg_220 = ap_const_lv10_310) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op173 <= (res_V_data_9_V_full_n and res_V_data_8_V_full_n and res_V_data_7_V_full_n and res_V_data_6_V_full_n and res_V_data_5_V_full_n and res_V_data_4_V_full_n and res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_15_V_full_n and res_V_data_14_V_full_n and res_V_data_13_V_full_n and res_V_data_12_V_full_n and res_V_data_11_V_full_n and res_V_data_10_V_full_n and res_V_data_0_V_full_n);
    lshr_ln708_1_fu_657_p4 <= kernel_data_V_1_5_ret_reg_1021(7 downto 1);
    lshr_ln708_2_fu_700_p4 <= kernel_data_V_1_5_ret_reg_1021(7 downto 3);
    lshr_ln708_3_fu_738_p4 <= kernel_data_V_1_6_ret_reg_1002(7 downto 1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_V_data_0_V_blk_n_assign_proc : process(res_V_data_0_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_0_V_blk_n <= res_V_data_0_V_full_n;
        else 
            res_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_0_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_0_V_4_fu_929_p2),10));

    res_V_data_0_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_10_V_blk_n_assign_proc : process(res_V_data_10_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_10_V_blk_n <= res_V_data_10_V_full_n;
        else 
            res_V_data_10_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_10_V_din <= acc_4_V_fu_871_p1;

    res_V_data_10_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_10_V_write <= ap_const_logic_1;
        else 
            res_V_data_10_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_11_V_blk_n_assign_proc : process(res_V_data_11_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_11_V_blk_n <= res_V_data_11_V_full_n;
        else 
            res_V_data_11_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        res_V_data_11_V_din <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_11_V_fu_918_p2),10));


    res_V_data_11_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_11_V_write <= ap_const_logic_1;
        else 
            res_V_data_11_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_12_V_blk_n_assign_proc : process(res_V_data_12_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_12_V_blk_n <= res_V_data_12_V_full_n;
        else 
            res_V_data_12_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_12_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(acc_12_V_fu_950_p2),10));

    res_V_data_12_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_12_V_write <= ap_const_logic_1;
        else 
            res_V_data_12_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_13_V_blk_n_assign_proc : process(res_V_data_13_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_13_V_blk_n <= res_V_data_13_V_full_n;
        else 
            res_V_data_13_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_13_V_din <= std_logic_vector(unsigned(zext_ln703_4_fu_940_p1) + unsigned(sext_ln708_fu_853_p1));

    res_V_data_13_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_13_V_write <= ap_const_logic_1;
        else 
            res_V_data_13_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_14_V_blk_n_assign_proc : process(res_V_data_14_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_14_V_blk_n <= res_V_data_14_V_full_n;
        else 
            res_V_data_14_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        res_V_data_14_V_din <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_14_V_fu_971_p2),10));


    res_V_data_14_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_14_V_write <= ap_const_logic_1;
        else 
            res_V_data_14_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_15_V_blk_n_assign_proc : process(res_V_data_15_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_15_V_blk_n <= res_V_data_15_V_full_n;
        else 
            res_V_data_15_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_15_V_din <= ap_const_lv10_0;

    res_V_data_15_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_15_V_write <= ap_const_logic_1;
        else 
            res_V_data_15_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_blk_n_assign_proc : process(res_V_data_1_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_1_V_blk_n <= res_V_data_1_V_full_n;
        else 
            res_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_1_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(acc_1_V_reg_1124),10));

    res_V_data_1_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_blk_n_assign_proc : process(res_V_data_2_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_2_V_blk_n <= res_V_data_2_V_full_n;
        else 
            res_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        res_V_data_2_V_din <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_2_V_fu_903_p2),10));


    res_V_data_2_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_3_V_blk_n_assign_proc : process(res_V_data_3_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_3_V_blk_n <= res_V_data_3_V_full_n;
        else 
            res_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_3_V_din <= ap_const_lv10_0;

    res_V_data_3_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_4_V_blk_n_assign_proc : process(res_V_data_4_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_4_V_blk_n <= res_V_data_4_V_full_n;
        else 
            res_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_4_V_din <= acc_4_V_fu_871_p1;

    res_V_data_4_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_4_V_write <= ap_const_logic_1;
        else 
            res_V_data_4_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_5_V_blk_n_assign_proc : process(res_V_data_5_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_5_V_blk_n <= res_V_data_5_V_full_n;
        else 
            res_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_5_V_din <= std_logic_vector(signed(sext_ln703_fu_893_p1) + signed(zext_ln708_fu_856_p1));

    res_V_data_5_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_5_V_write <= ap_const_logic_1;
        else 
            res_V_data_5_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_6_V_blk_n_assign_proc : process(res_V_data_6_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_6_V_blk_n <= res_V_data_6_V_full_n;
        else 
            res_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_6_V_din <= ap_const_lv10_0;

    res_V_data_6_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_6_V_write <= ap_const_logic_1;
        else 
            res_V_data_6_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_7_V_blk_n_assign_proc : process(res_V_data_7_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_7_V_blk_n <= res_V_data_7_V_full_n;
        else 
            res_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_7_V_din <= ap_const_lv10_3FE;

    res_V_data_7_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_7_V_write <= ap_const_logic_1;
        else 
            res_V_data_7_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_8_V_blk_n_assign_proc : process(res_V_data_8_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_8_V_blk_n <= res_V_data_8_V_full_n;
        else 
            res_V_data_8_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        res_V_data_8_V_din <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_8_V_fu_960_p2),10));


    res_V_data_8_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_8_V_write <= ap_const_logic_1;
        else 
            res_V_data_8_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_9_V_blk_n_assign_proc : process(res_V_data_9_V_full_n, ap_CS_fsm_state6, icmp_ln78_reg_988, and_ln272_2_reg_1041)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = and_ln272_2_reg_1041) and (icmp_ln78_reg_988 = ap_const_lv1_0))) then 
            res_V_data_9_V_blk_n <= res_V_data_9_V_full_n;
        else 
            res_V_data_9_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_9_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(acc_9_V_fu_882_p2),10));

    res_V_data_9_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op173, ap_predicate_op173_write_state6)
    begin
        if ((not(((io_acc_block_signal_op173 = ap_const_logic_0) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_predicate_op173_write_state6 = ap_const_boolean_1))) then 
            res_V_data_9_V_write <= ap_const_logic_1;
        else 
            res_V_data_9_V_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln303_fu_547_p3 <= 
        ap_const_lv32_2 when (icmp_ln272_1_fu_385_p2(0) = '1') else 
        add_ln303_fu_541_p2;
    select_ln308_fu_503_p3 <= 
        ap_const_lv32_2 when (icmp_ln272_fu_375_p2(0) = '1') else 
        add_ln308_fu_497_p2;
        sext_ln1118_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1118_fu_598_p2),12));

        sext_ln703_140_fu_879_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_246_reg_1114),9));

        sext_ln703_fu_893_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln703_200_reg_1119),10));

        sext_ln708_1_fu_865_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_243_reg_1093),9));

        sext_ln708_fu_853_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_239_reg_1078),10));

    shl_ln1118_1_fu_627_p3 <= (kernel_data_V_1_3_ret_reg_1008 & ap_const_lv2_0);
    shl_ln1118_2_fu_673_p3 <= (kernel_data_V_1_5_ret_reg_1021 & ap_const_lv2_0);
    shl_ln1118_3_fu_754_p3 <= (kernel_data_V_1_7_ret_reg_1029 & ap_const_lv2_0);
    shl_ln1118_4_fu_790_p3 <= (kernel_data_V_1_8_ret_reg_1035 & ap_const_lv2_0);
    shl_ln_fu_567_p3 <= (kernel_data_V_1_1_ret_reg_1014 & ap_const_lv2_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln1118_1_fu_608_p2 <= std_logic_vector(signed(sext_ln1118_fu_604_p1) - signed(zext_ln1116_fu_561_p1));
    sub_ln1118_2_fu_713_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(zext_ln1118_5_fu_680_p1));
    sub_ln1118_3_fu_801_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(zext_ln1118_9_fu_797_p1));
    sub_ln1118_fu_598_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(zext_ln1118_1_fu_574_p1));
    tmp_170_fu_395_p4 <= pY_2(31 downto 1);
    tmp_171_fu_415_p4 <= pX_2(31 downto 1);
    tmp_data_0_V_4_fu_929_p2 <= std_logic_vector(unsigned(zext_ln708_8_fu_868_p1) + unsigned(ap_const_lv6_1));
    tmp_fu_584_p4 <= add_ln1118_fu_578_p2(10 downto 3);
    zext_ln1116_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kernel_data_V_1_1_ret_reg_1014),12));
    zext_ln1118_1_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_567_p3),11));
    zext_ln1118_2_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kernel_data_V_1_3_ret_reg_1008),11));
    zext_ln1118_3_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1118_1_fu_627_p3),11));
    zext_ln1118_4_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kernel_data_V_1_5_ret_reg_1021),11));
    zext_ln1118_5_fu_680_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1118_2_fu_673_p3),11));
    zext_ln1118_6_fu_751_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kernel_data_V_1_7_ret_reg_1029),11));
    zext_ln1118_7_fu_761_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1118_3_fu_754_p3),11));
    zext_ln1118_8_fu_876_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln708_4_reg_1108),9));
    zext_ln1118_9_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1118_4_fu_790_p3),11));
    zext_ln1118_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kernel_data_V_1_1_ret_reg_1014),11));
    zext_ln703_1_fu_829_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln703_203_fu_823_p2),8));
    zext_ln703_4_fu_940_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln703_213_reg_1129),10));
    zext_ln708_1_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_1045),8));
    zext_ln708_2_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_584_p4),9));
    zext_ln708_3_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_45_reg_1083),9));
    zext_ln708_4_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_46_reg_1055),6));
    zext_ln708_5_fu_666_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln708_1_fu_657_p4),8));
    zext_ln708_6_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_47_reg_1088),9));
    zext_ln708_7_fu_709_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln708_2_fu_700_p4),8));
    zext_ln708_8_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_48_reg_1098),6));
    zext_ln708_9_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln708_3_fu_738_p4),8));
    zext_ln708_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln708_s_reg_1050),10));
end behav;
