// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax_latency_ap_fixed_ap_fixed_softmax_config13_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_ST_fsm_pp0_stage0 = "1";
const bool softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_boolean_1 = true;
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_boolean_0 = false;
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_6 = "110";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_F = "1111";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_11 = "10001";
const sc_lv<18> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv18_1FFFF = "11111111111111111";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_12 = "10010";
const sc_lv<1> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv1_1 = "1";
const sc_lv<18> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv18_20000 = "100000000000000000";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_8 = "1000";
const sc_lv<10> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv10_1FF = "111111111";
const sc_lv<10> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv10_200 = "1000000000";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_A = "1010";
const sc_lv<32> softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::ap_const_lv32_19 = "11001";

softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::softmax_latency_ap_fixed_ap_fixed_softmax_config13_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    exp_table1_U = new softmax_latency_ap_fixed_ap_fixed_softmax_config13_s_exp_bkb("exp_table1_U");
    exp_table1_U->clk(ap_clk);
    exp_table1_U->reset(ap_rst);
    exp_table1_U->address0(exp_table1_address0);
    exp_table1_U->ce0(exp_table1_ce0);
    exp_table1_U->q0(exp_table1_q0);
    exp_table1_U->address1(exp_table1_address1);
    exp_table1_U->ce1(exp_table1_ce1);
    exp_table1_U->q1(exp_table1_q1);
    exp_table1_U->address2(exp_table1_address2);
    exp_table1_U->ce2(exp_table1_ce2);
    exp_table1_U->q2(exp_table1_q2);
    exp_table1_U->address3(exp_table1_address3);
    exp_table1_U->ce3(exp_table1_ce3);
    exp_table1_U->q3(exp_table1_q3);
    exp_table1_U->address4(exp_table1_address4);
    exp_table1_U->ce4(exp_table1_ce4);
    exp_table1_U->q4(exp_table1_q4);
    invert_table2_U = new softmax_latency_ap_fixed_ap_fixed_softmax_config13_s_invecud("invert_table2_U");
    invert_table2_U->clk(ap_clk);
    invert_table2_U->reset(ap_rst);
    invert_table2_U->address0(invert_table2_address0);
    invert_table2_U->ce0(invert_table2_ce0);
    invert_table2_U->q0(invert_table2_q0);
    myproject_mul_mul_17ns_18s_26_3_1_U404 = new myproject_mul_mul_17ns_18s_26_3_1<1,3,17,18,26>("myproject_mul_mul_17ns_18s_26_3_1_U404");
    myproject_mul_mul_17ns_18s_26_3_1_U404->clk(ap_clk);
    myproject_mul_mul_17ns_18s_26_3_1_U404->reset(ap_rst);
    myproject_mul_mul_17ns_18s_26_3_1_U404->din0(grp_fu_581_p0);
    myproject_mul_mul_17ns_18s_26_3_1_U404->din1(grp_fu_581_p1);
    myproject_mul_mul_17ns_18s_26_3_1_U404->ce(grp_fu_581_ce);
    myproject_mul_mul_17ns_18s_26_3_1_U404->dout(grp_fu_581_p2);
    myproject_mul_mul_17ns_18s_26_3_1_U405 = new myproject_mul_mul_17ns_18s_26_3_1<1,3,17,18,26>("myproject_mul_mul_17ns_18s_26_3_1_U405");
    myproject_mul_mul_17ns_18s_26_3_1_U405->clk(ap_clk);
    myproject_mul_mul_17ns_18s_26_3_1_U405->reset(ap_rst);
    myproject_mul_mul_17ns_18s_26_3_1_U405->din0(grp_fu_587_p0);
    myproject_mul_mul_17ns_18s_26_3_1_U405->din1(grp_fu_587_p1);
    myproject_mul_mul_17ns_18s_26_3_1_U405->ce(grp_fu_587_ce);
    myproject_mul_mul_17ns_18s_26_3_1_U405->dout(grp_fu_587_p2);
    myproject_mul_mul_17ns_18s_26_3_1_U406 = new myproject_mul_mul_17ns_18s_26_3_1<1,3,17,18,26>("myproject_mul_mul_17ns_18s_26_3_1_U406");
    myproject_mul_mul_17ns_18s_26_3_1_U406->clk(ap_clk);
    myproject_mul_mul_17ns_18s_26_3_1_U406->reset(ap_rst);
    myproject_mul_mul_17ns_18s_26_3_1_U406->din0(grp_fu_593_p0);
    myproject_mul_mul_17ns_18s_26_3_1_U406->din1(grp_fu_593_p1);
    myproject_mul_mul_17ns_18s_26_3_1_U406->ce(grp_fu_593_ce);
    myproject_mul_mul_17ns_18s_26_3_1_U406->dout(grp_fu_593_p2);
    myproject_mul_mul_17ns_18s_26_3_1_U407 = new myproject_mul_mul_17ns_18s_26_3_1<1,3,17,18,26>("myproject_mul_mul_17ns_18s_26_3_1_U407");
    myproject_mul_mul_17ns_18s_26_3_1_U407->clk(ap_clk);
    myproject_mul_mul_17ns_18s_26_3_1_U407->reset(ap_rst);
    myproject_mul_mul_17ns_18s_26_3_1_U407->din0(grp_fu_599_p0);
    myproject_mul_mul_17ns_18s_26_3_1_U407->din1(grp_fu_599_p1);
    myproject_mul_mul_17ns_18s_26_3_1_U407->ce(grp_fu_599_ce);
    myproject_mul_mul_17ns_18s_26_3_1_U407->dout(grp_fu_599_p2);
    myproject_mul_mul_17ns_18s_26_3_1_U408 = new myproject_mul_mul_17ns_18s_26_3_1<1,3,17,18,26>("myproject_mul_mul_17ns_18s_26_3_1_U408");
    myproject_mul_mul_17ns_18s_26_3_1_U408->clk(ap_clk);
    myproject_mul_mul_17ns_18s_26_3_1_U408->reset(ap_rst);
    myproject_mul_mul_17ns_18s_26_3_1_U408->din0(grp_fu_605_p0);
    myproject_mul_mul_17ns_18s_26_3_1_U408->din1(grp_fu_605_p1);
    myproject_mul_mul_17ns_18s_26_3_1_U408->ce(grp_fu_605_ce);
    myproject_mul_mul_17ns_18s_26_3_1_U408->dout(grp_fu_605_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_ap_idle_pp0_0to9);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to9 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_reg_739 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_1_reg_744 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_2_reg_749 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_3_reg_754 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_4_reg_759 );

    SC_METHOD(thread_exp_table1_address0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_fu_178_p1 );

    SC_METHOD(thread_exp_table1_address1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_1_fu_193_p1 );

    SC_METHOD(thread_exp_table1_address2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_2_fu_208_p1 );

    SC_METHOD(thread_exp_table1_address3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln251_3_fu_223_p1 );

    SC_METHOD(thread_exp_table1_address4);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln251_4_fu_250_p1 );

    SC_METHOD(thread_exp_table1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce4);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_grp_fu_581_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_grp_fu_581_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( grp_fu_581_p00 );

    SC_METHOD(thread_grp_fu_581_p00);
    sensitive << ( exp_res_0_V_reg_636_pp0_iter6_reg );

    SC_METHOD(thread_grp_fu_581_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( sext_ln1116_fu_488_p1 );

    SC_METHOD(thread_grp_fu_587_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_grp_fu_587_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( grp_fu_587_p00 );

    SC_METHOD(thread_grp_fu_587_p00);
    sensitive << ( exp_res_1_V_reg_642_pp0_iter6_reg );

    SC_METHOD(thread_grp_fu_587_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( sext_ln1116_fu_488_p1 );

    SC_METHOD(thread_grp_fu_593_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_grp_fu_593_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( grp_fu_593_p00 );

    SC_METHOD(thread_grp_fu_593_p00);
    sensitive << ( exp_res_2_V_reg_648_pp0_iter6_reg );

    SC_METHOD(thread_grp_fu_593_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( sext_ln1116_fu_488_p1 );

    SC_METHOD(thread_grp_fu_599_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_grp_fu_599_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( grp_fu_599_p00 );

    SC_METHOD(thread_grp_fu_599_p00);
    sensitive << ( exp_res_3_V_reg_654_pp0_iter6_reg );

    SC_METHOD(thread_grp_fu_599_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( sext_ln1116_fu_488_p1 );

    SC_METHOD(thread_grp_fu_605_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_grp_fu_605_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( grp_fu_605_p00 );

    SC_METHOD(thread_grp_fu_605_p00);
    sensitive << ( exp_res_4_V_reg_677_pp0_iter6_reg );

    SC_METHOD(thread_grp_fu_605_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( sext_ln1116_fu_488_p1 );

    SC_METHOD(thread_invert_table2_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( zext_ln259_fu_484_p1 );

    SC_METHOD(thread_invert_table2_ce0);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_lhs_V_1_fu_387_p1);
    sensitive << ( p_Val2_11_reg_684 );

    SC_METHOD(thread_lhs_V_fu_298_p1);
    sensitive << ( p_Val2_7_reg_665 );

    SC_METHOD(thread_or_ln340_1_fu_444_p2);
    sensitive << ( p_Result_18_fu_412_p3 );
    sensitive << ( xor_ln340_3_fu_438_p2 );

    SC_METHOD(thread_or_ln340_fu_354_p2);
    sensitive << ( p_Result_16_fu_322_p3 );
    sensitive << ( xor_ln340_1_fu_348_p2 );

    SC_METHOD(thread_p_Result_14_fu_282_p3);
    sensitive << ( p_Val2_6_fu_276_p2 );

    SC_METHOD(thread_p_Result_15_fu_310_p3);
    sensitive << ( ret_V_fu_304_p2 );

    SC_METHOD(thread_p_Result_16_fu_322_p3);
    sensitive << ( p_Val2_10_fu_318_p2 );

    SC_METHOD(thread_p_Result_17_fu_399_p3);
    sensitive << ( ret_V_1_fu_393_p2 );

    SC_METHOD(thread_p_Result_18_fu_412_p3);
    sensitive << ( p_Val2_14_fu_407_p2 );

    SC_METHOD(thread_p_Result_s_fu_260_p3);
    sensitive << ( p_Val2_3_fu_254_p2 );

    SC_METHOD(thread_p_Val2_10_fu_318_p2);
    sensitive << ( p_Val2_7_reg_665 );
    sensitive << ( p_Val2_8_reg_671 );

    SC_METHOD(thread_p_Val2_11_fu_376_p3);
    sensitive << ( or_ln340_fu_354_p2 );
    sensitive << ( select_ln340_fu_360_p3 );
    sensitive << ( select_ln388_fu_368_p3 );

    SC_METHOD(thread_p_Val2_14_fu_407_p2);
    sensitive << ( p_Val2_11_reg_684 );
    sensitive << ( zext_ln203_4_fu_384_p1 );

    SC_METHOD(thread_p_Val2_2_fu_241_p1);
    sensitive << ( exp_res_1_V_reg_642 );

    SC_METHOD(thread_p_Val2_3_fu_254_p2);
    sensitive << ( p_Val2_2_fu_241_p1 );
    sensitive << ( p_Val2_s_fu_238_p1 );

    SC_METHOD(thread_p_Val2_4_fu_244_p1);
    sensitive << ( exp_res_2_V_reg_648 );

    SC_METHOD(thread_p_Val2_5_fu_247_p1);
    sensitive << ( exp_res_3_V_reg_654 );

    SC_METHOD(thread_p_Val2_6_fu_276_p2);
    sensitive << ( p_Val2_5_fu_247_p1 );
    sensitive << ( p_Val2_4_fu_244_p1 );

    SC_METHOD(thread_p_Val2_7_fu_268_p3);
    sensitive << ( p_Val2_3_fu_254_p2 );
    sensitive << ( p_Result_s_fu_260_p3 );

    SC_METHOD(thread_p_Val2_8_fu_290_p3);
    sensitive << ( p_Val2_6_fu_276_p2 );
    sensitive << ( p_Result_14_fu_282_p3 );

    SC_METHOD(thread_p_Val2_s_fu_238_p1);
    sensitive << ( exp_res_0_V_reg_636 );

    SC_METHOD(thread_ret_V_1_fu_393_p2);
    sensitive << ( lhs_V_1_fu_387_p1 );
    sensitive << ( rhs_V_1_fu_390_p1 );

    SC_METHOD(thread_ret_V_fu_304_p2);
    sensitive << ( lhs_V_fu_298_p1 );
    sensitive << ( rhs_V_fu_301_p1 );

    SC_METHOD(thread_rhs_V_1_fu_390_p1);
    sensitive << ( exp_res_4_V_reg_677 );

    SC_METHOD(thread_rhs_V_fu_301_p1);
    sensitive << ( p_Val2_8_reg_671 );

    SC_METHOD(thread_select_ln340_3_fu_460_p3);
    sensitive << ( xor_ln340_2_fu_432_p2 );
    sensitive << ( tmp_fu_450_p4 );

    SC_METHOD(thread_select_ln340_fu_360_p3);
    sensitive << ( p_Val2_10_fu_318_p2 );
    sensitive << ( xor_ln340_fu_342_p2 );

    SC_METHOD(thread_select_ln388_1_fu_468_p3);
    sensitive << ( tmp_fu_450_p4 );
    sensitive << ( underflow_1_fu_426_p2 );

    SC_METHOD(thread_select_ln388_fu_368_p3);
    sensitive << ( p_Val2_10_fu_318_p2 );
    sensitive << ( underflow_fu_336_p2 );

    SC_METHOD(thread_sext_ln1116_fu_488_p1);
    sensitive << ( inv_exp_sum_V_reg_700 );

    SC_METHOD(thread_tmp_fu_450_p4);
    sensitive << ( p_Val2_14_fu_407_p2 );

    SC_METHOD(thread_underflow_1_fu_426_p2);
    sensitive << ( p_Result_17_fu_399_p3 );
    sensitive << ( xor_ln786_1_fu_420_p2 );

    SC_METHOD(thread_underflow_fu_336_p2);
    sensitive << ( p_Result_15_fu_310_p3 );
    sensitive << ( xor_ln786_fu_330_p2 );

    SC_METHOD(thread_xor_ln340_1_fu_348_p2);
    sensitive << ( p_Result_15_fu_310_p3 );

    SC_METHOD(thread_xor_ln340_2_fu_432_p2);
    sensitive << ( p_Result_18_fu_412_p3 );
    sensitive << ( p_Result_17_fu_399_p3 );

    SC_METHOD(thread_xor_ln340_3_fu_438_p2);
    sensitive << ( p_Result_17_fu_399_p3 );

    SC_METHOD(thread_xor_ln340_fu_342_p2);
    sensitive << ( p_Result_16_fu_322_p3 );
    sensitive << ( p_Result_15_fu_310_p3 );

    SC_METHOD(thread_xor_ln786_1_fu_420_p2);
    sensitive << ( p_Result_18_fu_412_p3 );

    SC_METHOD(thread_xor_ln786_fu_330_p2);
    sensitive << ( p_Result_16_fu_322_p3 );

    SC_METHOD(thread_y_V_1_fu_183_p4);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_y_V_2_fu_198_p4);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_y_V_3_fu_213_p4);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_y_V_5_fu_476_p3);
    sensitive << ( or_ln340_1_fu_444_p2 );
    sensitive << ( select_ln340_3_fu_460_p3 );
    sensitive << ( select_ln388_1_fu_468_p3 );

    SC_METHOD(thread_y_V_fu_168_p4);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_zext_ln203_4_fu_384_p1);
    sensitive << ( exp_res_4_V_reg_677 );

    SC_METHOD(thread_zext_ln251_1_fu_193_p1);
    sensitive << ( y_V_1_fu_183_p4 );

    SC_METHOD(thread_zext_ln251_2_fu_208_p1);
    sensitive << ( y_V_2_fu_198_p4 );

    SC_METHOD(thread_zext_ln251_3_fu_223_p1);
    sensitive << ( y_V_3_fu_213_p4 );

    SC_METHOD(thread_zext_ln251_4_fu_250_p1);
    sensitive << ( y_V_4_reg_631_pp0_iter1_reg );

    SC_METHOD(thread_zext_ln251_fu_178_p1);
    sensitive << ( y_V_fu_168_p4 );

    SC_METHOD(thread_zext_ln259_fu_484_p1);
    sensitive << ( y_V_5_reg_690 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_latency_ap_fixed_ap_fixed_softmax_config13_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7, "ap_block_state8_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8, "ap_block_state9_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9, "ap_block_state10_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10, "ap_block_state11_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exp_table1_address0, "exp_table1_address0");
    sc_trace(mVcdFile, exp_table1_ce0, "exp_table1_ce0");
    sc_trace(mVcdFile, exp_table1_q0, "exp_table1_q0");
    sc_trace(mVcdFile, exp_table1_address1, "exp_table1_address1");
    sc_trace(mVcdFile, exp_table1_ce1, "exp_table1_ce1");
    sc_trace(mVcdFile, exp_table1_q1, "exp_table1_q1");
    sc_trace(mVcdFile, exp_table1_address2, "exp_table1_address2");
    sc_trace(mVcdFile, exp_table1_ce2, "exp_table1_ce2");
    sc_trace(mVcdFile, exp_table1_q2, "exp_table1_q2");
    sc_trace(mVcdFile, exp_table1_address3, "exp_table1_address3");
    sc_trace(mVcdFile, exp_table1_ce3, "exp_table1_ce3");
    sc_trace(mVcdFile, exp_table1_q3, "exp_table1_q3");
    sc_trace(mVcdFile, exp_table1_address4, "exp_table1_address4");
    sc_trace(mVcdFile, exp_table1_ce4, "exp_table1_ce4");
    sc_trace(mVcdFile, exp_table1_q4, "exp_table1_q4");
    sc_trace(mVcdFile, invert_table2_address0, "invert_table2_address0");
    sc_trace(mVcdFile, invert_table2_ce0, "invert_table2_ce0");
    sc_trace(mVcdFile, invert_table2_q0, "invert_table2_q0");
    sc_trace(mVcdFile, y_V_4_reg_631, "y_V_4_reg_631");
    sc_trace(mVcdFile, y_V_4_reg_631_pp0_iter1_reg, "y_V_4_reg_631_pp0_iter1_reg");
    sc_trace(mVcdFile, exp_res_0_V_reg_636, "exp_res_0_V_reg_636");
    sc_trace(mVcdFile, exp_res_0_V_reg_636_pp0_iter2_reg, "exp_res_0_V_reg_636_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_0_V_reg_636_pp0_iter3_reg, "exp_res_0_V_reg_636_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_0_V_reg_636_pp0_iter4_reg, "exp_res_0_V_reg_636_pp0_iter4_reg");
    sc_trace(mVcdFile, exp_res_0_V_reg_636_pp0_iter5_reg, "exp_res_0_V_reg_636_pp0_iter5_reg");
    sc_trace(mVcdFile, exp_res_0_V_reg_636_pp0_iter6_reg, "exp_res_0_V_reg_636_pp0_iter6_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_642, "exp_res_1_V_reg_642");
    sc_trace(mVcdFile, exp_res_1_V_reg_642_pp0_iter2_reg, "exp_res_1_V_reg_642_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_642_pp0_iter3_reg, "exp_res_1_V_reg_642_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_642_pp0_iter4_reg, "exp_res_1_V_reg_642_pp0_iter4_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_642_pp0_iter5_reg, "exp_res_1_V_reg_642_pp0_iter5_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_642_pp0_iter6_reg, "exp_res_1_V_reg_642_pp0_iter6_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_648, "exp_res_2_V_reg_648");
    sc_trace(mVcdFile, exp_res_2_V_reg_648_pp0_iter2_reg, "exp_res_2_V_reg_648_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_648_pp0_iter3_reg, "exp_res_2_V_reg_648_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_648_pp0_iter4_reg, "exp_res_2_V_reg_648_pp0_iter4_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_648_pp0_iter5_reg, "exp_res_2_V_reg_648_pp0_iter5_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_648_pp0_iter6_reg, "exp_res_2_V_reg_648_pp0_iter6_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_654, "exp_res_3_V_reg_654");
    sc_trace(mVcdFile, exp_res_3_V_reg_654_pp0_iter2_reg, "exp_res_3_V_reg_654_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_654_pp0_iter3_reg, "exp_res_3_V_reg_654_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_654_pp0_iter4_reg, "exp_res_3_V_reg_654_pp0_iter4_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_654_pp0_iter5_reg, "exp_res_3_V_reg_654_pp0_iter5_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_654_pp0_iter6_reg, "exp_res_3_V_reg_654_pp0_iter6_reg");
    sc_trace(mVcdFile, p_Val2_7_fu_268_p3, "p_Val2_7_fu_268_p3");
    sc_trace(mVcdFile, p_Val2_7_reg_665, "p_Val2_7_reg_665");
    sc_trace(mVcdFile, p_Val2_8_fu_290_p3, "p_Val2_8_fu_290_p3");
    sc_trace(mVcdFile, p_Val2_8_reg_671, "p_Val2_8_reg_671");
    sc_trace(mVcdFile, exp_res_4_V_reg_677, "exp_res_4_V_reg_677");
    sc_trace(mVcdFile, exp_res_4_V_reg_677_pp0_iter4_reg, "exp_res_4_V_reg_677_pp0_iter4_reg");
    sc_trace(mVcdFile, exp_res_4_V_reg_677_pp0_iter5_reg, "exp_res_4_V_reg_677_pp0_iter5_reg");
    sc_trace(mVcdFile, exp_res_4_V_reg_677_pp0_iter6_reg, "exp_res_4_V_reg_677_pp0_iter6_reg");
    sc_trace(mVcdFile, p_Val2_11_fu_376_p3, "p_Val2_11_fu_376_p3");
    sc_trace(mVcdFile, p_Val2_11_reg_684, "p_Val2_11_reg_684");
    sc_trace(mVcdFile, y_V_5_fu_476_p3, "y_V_5_fu_476_p3");
    sc_trace(mVcdFile, y_V_5_reg_690, "y_V_5_reg_690");
    sc_trace(mVcdFile, inv_exp_sum_V_reg_700, "inv_exp_sum_V_reg_700");
    sc_trace(mVcdFile, sext_ln1116_fu_488_p1, "sext_ln1116_fu_488_p1");
    sc_trace(mVcdFile, grp_fu_581_p2, "grp_fu_581_p2");
    sc_trace(mVcdFile, mul_ln1118_reg_739, "mul_ln1118_reg_739");
    sc_trace(mVcdFile, grp_fu_587_p2, "grp_fu_587_p2");
    sc_trace(mVcdFile, mul_ln1118_1_reg_744, "mul_ln1118_1_reg_744");
    sc_trace(mVcdFile, grp_fu_593_p2, "grp_fu_593_p2");
    sc_trace(mVcdFile, mul_ln1118_2_reg_749, "mul_ln1118_2_reg_749");
    sc_trace(mVcdFile, grp_fu_599_p2, "grp_fu_599_p2");
    sc_trace(mVcdFile, mul_ln1118_3_reg_754, "mul_ln1118_3_reg_754");
    sc_trace(mVcdFile, grp_fu_605_p2, "grp_fu_605_p2");
    sc_trace(mVcdFile, mul_ln1118_4_reg_759, "mul_ln1118_4_reg_759");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln251_fu_178_p1, "zext_ln251_fu_178_p1");
    sc_trace(mVcdFile, zext_ln251_1_fu_193_p1, "zext_ln251_1_fu_193_p1");
    sc_trace(mVcdFile, zext_ln251_2_fu_208_p1, "zext_ln251_2_fu_208_p1");
    sc_trace(mVcdFile, zext_ln251_3_fu_223_p1, "zext_ln251_3_fu_223_p1");
    sc_trace(mVcdFile, zext_ln251_4_fu_250_p1, "zext_ln251_4_fu_250_p1");
    sc_trace(mVcdFile, zext_ln259_fu_484_p1, "zext_ln259_fu_484_p1");
    sc_trace(mVcdFile, y_V_fu_168_p4, "y_V_fu_168_p4");
    sc_trace(mVcdFile, y_V_1_fu_183_p4, "y_V_1_fu_183_p4");
    sc_trace(mVcdFile, y_V_2_fu_198_p4, "y_V_2_fu_198_p4");
    sc_trace(mVcdFile, y_V_3_fu_213_p4, "y_V_3_fu_213_p4");
    sc_trace(mVcdFile, p_Val2_2_fu_241_p1, "p_Val2_2_fu_241_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_238_p1, "p_Val2_s_fu_238_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_254_p2, "p_Val2_3_fu_254_p2");
    sc_trace(mVcdFile, p_Result_s_fu_260_p3, "p_Result_s_fu_260_p3");
    sc_trace(mVcdFile, p_Val2_5_fu_247_p1, "p_Val2_5_fu_247_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_244_p1, "p_Val2_4_fu_244_p1");
    sc_trace(mVcdFile, p_Val2_6_fu_276_p2, "p_Val2_6_fu_276_p2");
    sc_trace(mVcdFile, p_Result_14_fu_282_p3, "p_Result_14_fu_282_p3");
    sc_trace(mVcdFile, lhs_V_fu_298_p1, "lhs_V_fu_298_p1");
    sc_trace(mVcdFile, rhs_V_fu_301_p1, "rhs_V_fu_301_p1");
    sc_trace(mVcdFile, ret_V_fu_304_p2, "ret_V_fu_304_p2");
    sc_trace(mVcdFile, p_Val2_10_fu_318_p2, "p_Val2_10_fu_318_p2");
    sc_trace(mVcdFile, p_Result_16_fu_322_p3, "p_Result_16_fu_322_p3");
    sc_trace(mVcdFile, p_Result_15_fu_310_p3, "p_Result_15_fu_310_p3");
    sc_trace(mVcdFile, xor_ln786_fu_330_p2, "xor_ln786_fu_330_p2");
    sc_trace(mVcdFile, xor_ln340_1_fu_348_p2, "xor_ln340_1_fu_348_p2");
    sc_trace(mVcdFile, xor_ln340_fu_342_p2, "xor_ln340_fu_342_p2");
    sc_trace(mVcdFile, underflow_fu_336_p2, "underflow_fu_336_p2");
    sc_trace(mVcdFile, or_ln340_fu_354_p2, "or_ln340_fu_354_p2");
    sc_trace(mVcdFile, select_ln340_fu_360_p3, "select_ln340_fu_360_p3");
    sc_trace(mVcdFile, select_ln388_fu_368_p3, "select_ln388_fu_368_p3");
    sc_trace(mVcdFile, lhs_V_1_fu_387_p1, "lhs_V_1_fu_387_p1");
    sc_trace(mVcdFile, rhs_V_1_fu_390_p1, "rhs_V_1_fu_390_p1");
    sc_trace(mVcdFile, ret_V_1_fu_393_p2, "ret_V_1_fu_393_p2");
    sc_trace(mVcdFile, zext_ln203_4_fu_384_p1, "zext_ln203_4_fu_384_p1");
    sc_trace(mVcdFile, p_Val2_14_fu_407_p2, "p_Val2_14_fu_407_p2");
    sc_trace(mVcdFile, p_Result_18_fu_412_p3, "p_Result_18_fu_412_p3");
    sc_trace(mVcdFile, p_Result_17_fu_399_p3, "p_Result_17_fu_399_p3");
    sc_trace(mVcdFile, xor_ln786_1_fu_420_p2, "xor_ln786_1_fu_420_p2");
    sc_trace(mVcdFile, xor_ln340_3_fu_438_p2, "xor_ln340_3_fu_438_p2");
    sc_trace(mVcdFile, xor_ln340_2_fu_432_p2, "xor_ln340_2_fu_432_p2");
    sc_trace(mVcdFile, tmp_fu_450_p4, "tmp_fu_450_p4");
    sc_trace(mVcdFile, underflow_1_fu_426_p2, "underflow_1_fu_426_p2");
    sc_trace(mVcdFile, or_ln340_1_fu_444_p2, "or_ln340_1_fu_444_p2");
    sc_trace(mVcdFile, select_ln340_3_fu_460_p3, "select_ln340_3_fu_460_p3");
    sc_trace(mVcdFile, select_ln388_1_fu_468_p3, "select_ln388_1_fu_468_p3");
    sc_trace(mVcdFile, grp_fu_581_p0, "grp_fu_581_p0");
    sc_trace(mVcdFile, grp_fu_581_p1, "grp_fu_581_p1");
    sc_trace(mVcdFile, grp_fu_587_p0, "grp_fu_587_p0");
    sc_trace(mVcdFile, grp_fu_587_p1, "grp_fu_587_p1");
    sc_trace(mVcdFile, grp_fu_593_p0, "grp_fu_593_p0");
    sc_trace(mVcdFile, grp_fu_593_p1, "grp_fu_593_p1");
    sc_trace(mVcdFile, grp_fu_599_p0, "grp_fu_599_p0");
    sc_trace(mVcdFile, grp_fu_599_p1, "grp_fu_599_p1");
    sc_trace(mVcdFile, grp_fu_605_p0, "grp_fu_605_p0");
    sc_trace(mVcdFile, grp_fu_605_p1, "grp_fu_605_p1");
    sc_trace(mVcdFile, grp_fu_581_ce, "grp_fu_581_ce");
    sc_trace(mVcdFile, grp_fu_587_ce, "grp_fu_587_ce");
    sc_trace(mVcdFile, grp_fu_593_ce, "grp_fu_593_ce");
    sc_trace(mVcdFile, grp_fu_599_ce, "grp_fu_599_ce");
    sc_trace(mVcdFile, grp_fu_605_ce, "grp_fu_605_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to9, "ap_idle_pp0_0to9");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_581_p00, "grp_fu_581_p00");
    sc_trace(mVcdFile, grp_fu_587_p00, "grp_fu_587_p00");
    sc_trace(mVcdFile, grp_fu_593_p00, "grp_fu_593_p00");
    sc_trace(mVcdFile, grp_fu_599_p00, "grp_fu_599_p00");
    sc_trace(mVcdFile, grp_fu_605_p00, "grp_fu_605_p00");
#endif

    }
}

softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::~softmax_latency_ap_fixed_ap_fixed_softmax_config13_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete exp_table1_U;
    delete invert_table2_U;
    delete myproject_mul_mul_17ns_18s_26_3_1_U404;
    delete myproject_mul_mul_17ns_18s_26_3_1_U405;
    delete myproject_mul_mul_17ns_18s_26_3_1_U406;
    delete myproject_mul_mul_17ns_18s_26_3_1_U407;
    delete myproject_mul_mul_17ns_18s_26_3_1_U408;
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_res_0_V_reg_636 = exp_table1_q0.read();
        exp_res_1_V_reg_642 = exp_table1_q1.read();
        exp_res_2_V_reg_648 = exp_table1_q2.read();
        exp_res_3_V_reg_654 = exp_table1_q3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        exp_res_0_V_reg_636_pp0_iter2_reg = exp_res_0_V_reg_636.read();
        exp_res_0_V_reg_636_pp0_iter3_reg = exp_res_0_V_reg_636_pp0_iter2_reg.read();
        exp_res_0_V_reg_636_pp0_iter4_reg = exp_res_0_V_reg_636_pp0_iter3_reg.read();
        exp_res_0_V_reg_636_pp0_iter5_reg = exp_res_0_V_reg_636_pp0_iter4_reg.read();
        exp_res_0_V_reg_636_pp0_iter6_reg = exp_res_0_V_reg_636_pp0_iter5_reg.read();
        exp_res_1_V_reg_642_pp0_iter2_reg = exp_res_1_V_reg_642.read();
        exp_res_1_V_reg_642_pp0_iter3_reg = exp_res_1_V_reg_642_pp0_iter2_reg.read();
        exp_res_1_V_reg_642_pp0_iter4_reg = exp_res_1_V_reg_642_pp0_iter3_reg.read();
        exp_res_1_V_reg_642_pp0_iter5_reg = exp_res_1_V_reg_642_pp0_iter4_reg.read();
        exp_res_1_V_reg_642_pp0_iter6_reg = exp_res_1_V_reg_642_pp0_iter5_reg.read();
        exp_res_2_V_reg_648_pp0_iter2_reg = exp_res_2_V_reg_648.read();
        exp_res_2_V_reg_648_pp0_iter3_reg = exp_res_2_V_reg_648_pp0_iter2_reg.read();
        exp_res_2_V_reg_648_pp0_iter4_reg = exp_res_2_V_reg_648_pp0_iter3_reg.read();
        exp_res_2_V_reg_648_pp0_iter5_reg = exp_res_2_V_reg_648_pp0_iter4_reg.read();
        exp_res_2_V_reg_648_pp0_iter6_reg = exp_res_2_V_reg_648_pp0_iter5_reg.read();
        exp_res_3_V_reg_654_pp0_iter2_reg = exp_res_3_V_reg_654.read();
        exp_res_3_V_reg_654_pp0_iter3_reg = exp_res_3_V_reg_654_pp0_iter2_reg.read();
        exp_res_3_V_reg_654_pp0_iter4_reg = exp_res_3_V_reg_654_pp0_iter3_reg.read();
        exp_res_3_V_reg_654_pp0_iter5_reg = exp_res_3_V_reg_654_pp0_iter4_reg.read();
        exp_res_3_V_reg_654_pp0_iter6_reg = exp_res_3_V_reg_654_pp0_iter5_reg.read();
        exp_res_4_V_reg_677_pp0_iter4_reg = exp_res_4_V_reg_677.read();
        exp_res_4_V_reg_677_pp0_iter5_reg = exp_res_4_V_reg_677_pp0_iter4_reg.read();
        exp_res_4_V_reg_677_pp0_iter6_reg = exp_res_4_V_reg_677_pp0_iter5_reg.read();
        inv_exp_sum_V_reg_700 = invert_table2_q0.read();
        mul_ln1118_1_reg_744 = grp_fu_587_p2.read();
        mul_ln1118_2_reg_749 = grp_fu_593_p2.read();
        mul_ln1118_3_reg_754 = grp_fu_599_p2.read();
        mul_ln1118_4_reg_759 = grp_fu_605_p2.read();
        mul_ln1118_reg_739 = grp_fu_581_p2.read();
        p_Val2_11_reg_684 = p_Val2_11_fu_376_p3.read();
        p_Val2_7_reg_665 = p_Val2_7_fu_268_p3.read();
        p_Val2_8_reg_671 = p_Val2_8_fu_290_p3.read();
        y_V_5_reg_690 = y_V_5_fu_476_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        exp_res_4_V_reg_677 = exp_table1_q4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        y_V_4_reg_631 = data_4_V_read.read().range(15, 6);
        y_V_4_reg_631_pp0_iter1_reg = y_V_4_reg_631.read();
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read())) || esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state10_pp0_stage0_iter9() {
    ap_block_state10_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state11_pp0_stage0_iter10() {
    ap_block_state11_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state8_pp0_stage0_iter7() {
    ap_block_state8_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_block_state9_pp0_stage0_iter8() {
    ap_block_state9_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_idle_pp0_0to9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()))) {
        ap_idle_pp0_0to9 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to9 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to9.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_return_0() {
    ap_return_0 = mul_ln1118_reg_739.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_return_1() {
    ap_return_1 = mul_ln1118_1_reg_744.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_return_2() {
    ap_return_2 = mul_ln1118_2_reg_749.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_return_3() {
    ap_return_3 = mul_ln1118_3_reg_754.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_return_4() {
    ap_return_4 = mul_ln1118_4_reg_759.read().range(25, 10);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_address0() {
    exp_table1_address0 =  (sc_lv<10>) (zext_ln251_fu_178_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_address1() {
    exp_table1_address1 =  (sc_lv<10>) (zext_ln251_1_fu_193_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_address2() {
    exp_table1_address2 =  (sc_lv<10>) (zext_ln251_2_fu_208_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_address3() {
    exp_table1_address3 =  (sc_lv<10>) (zext_ln251_3_fu_223_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_address4() {
    exp_table1_address4 =  (sc_lv<10>) (zext_ln251_4_fu_250_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        exp_table1_ce0 = ap_const_logic_1;
    } else {
        exp_table1_ce0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        exp_table1_ce1 = ap_const_logic_1;
    } else {
        exp_table1_ce1 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_ce2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        exp_table1_ce2 = ap_const_logic_1;
    } else {
        exp_table1_ce2 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_ce3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        exp_table1_ce3 = ap_const_logic_1;
    } else {
        exp_table1_ce3 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_exp_table1_ce4() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        exp_table1_ce4 = ap_const_logic_1;
    } else {
        exp_table1_ce4 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_581_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()))) {
        grp_fu_581_ce = ap_const_logic_1;
    } else {
        grp_fu_581_ce = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_581_p0() {
    grp_fu_581_p0 =  (sc_lv<17>) (grp_fu_581_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_581_p00() {
    grp_fu_581_p00 = esl_zext<26,17>(exp_res_0_V_reg_636_pp0_iter6_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_581_p1() {
    grp_fu_581_p1 =  (sc_lv<18>) (sext_ln1116_fu_488_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_587_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()))) {
        grp_fu_587_ce = ap_const_logic_1;
    } else {
        grp_fu_587_ce = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_587_p0() {
    grp_fu_587_p0 =  (sc_lv<17>) (grp_fu_587_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_587_p00() {
    grp_fu_587_p00 = esl_zext<26,17>(exp_res_1_V_reg_642_pp0_iter6_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_587_p1() {
    grp_fu_587_p1 =  (sc_lv<18>) (sext_ln1116_fu_488_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_593_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()))) {
        grp_fu_593_ce = ap_const_logic_1;
    } else {
        grp_fu_593_ce = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_593_p0() {
    grp_fu_593_p0 =  (sc_lv<17>) (grp_fu_593_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_593_p00() {
    grp_fu_593_p00 = esl_zext<26,17>(exp_res_2_V_reg_648_pp0_iter6_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_593_p1() {
    grp_fu_593_p1 =  (sc_lv<18>) (sext_ln1116_fu_488_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_599_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()))) {
        grp_fu_599_ce = ap_const_logic_1;
    } else {
        grp_fu_599_ce = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_599_p0() {
    grp_fu_599_p0 =  (sc_lv<17>) (grp_fu_599_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_599_p00() {
    grp_fu_599_p00 = esl_zext<26,17>(exp_res_3_V_reg_654_pp0_iter6_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_599_p1() {
    grp_fu_599_p1 =  (sc_lv<18>) (sext_ln1116_fu_488_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_605_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()))) {
        grp_fu_605_ce = ap_const_logic_1;
    } else {
        grp_fu_605_ce = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_605_p0() {
    grp_fu_605_p0 =  (sc_lv<17>) (grp_fu_605_p00.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_605_p00() {
    grp_fu_605_p00 = esl_zext<26,17>(exp_res_4_V_reg_677_pp0_iter6_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_grp_fu_605_p1() {
    grp_fu_605_p1 =  (sc_lv<18>) (sext_ln1116_fu_488_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_invert_table2_address0() {
    invert_table2_address0 =  (sc_lv<10>) (zext_ln259_fu_484_p1.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_invert_table2_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        invert_table2_ce0 = ap_const_logic_1;
    } else {
        invert_table2_ce0 = ap_const_logic_0;
    }
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_lhs_V_1_fu_387_p1() {
    lhs_V_1_fu_387_p1 = esl_sext<19,18>(p_Val2_11_reg_684.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_lhs_V_fu_298_p1() {
    lhs_V_fu_298_p1 = esl_sext<19,18>(p_Val2_7_reg_665.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_or_ln340_1_fu_444_p2() {
    or_ln340_1_fu_444_p2 = (p_Result_18_fu_412_p3.read() | xor_ln340_3_fu_438_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_or_ln340_fu_354_p2() {
    or_ln340_fu_354_p2 = (p_Result_16_fu_322_p3.read() | xor_ln340_1_fu_348_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Result_14_fu_282_p3() {
    p_Result_14_fu_282_p3 = p_Val2_6_fu_276_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Result_15_fu_310_p3() {
    p_Result_15_fu_310_p3 = ret_V_fu_304_p2.read().range(18, 18);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Result_16_fu_322_p3() {
    p_Result_16_fu_322_p3 = p_Val2_10_fu_318_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Result_17_fu_399_p3() {
    p_Result_17_fu_399_p3 = ret_V_1_fu_393_p2.read().range(18, 18);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Result_18_fu_412_p3() {
    p_Result_18_fu_412_p3 = p_Val2_14_fu_407_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Result_s_fu_260_p3() {
    p_Result_s_fu_260_p3 = p_Val2_3_fu_254_p2.read().range(17, 17);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_10_fu_318_p2() {
    p_Val2_10_fu_318_p2 = (!p_Val2_8_reg_671.read().is_01() || !p_Val2_7_reg_665.read().is_01())? sc_lv<18>(): (sc_bigint<18>(p_Val2_8_reg_671.read()) + sc_bigint<18>(p_Val2_7_reg_665.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_11_fu_376_p3() {
    p_Val2_11_fu_376_p3 = (!or_ln340_fu_354_p2.read()[0].is_01())? sc_lv<18>(): ((or_ln340_fu_354_p2.read()[0].to_bool())? select_ln340_fu_360_p3.read(): select_ln388_fu_368_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_14_fu_407_p2() {
    p_Val2_14_fu_407_p2 = (!p_Val2_11_reg_684.read().is_01() || !zext_ln203_4_fu_384_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(p_Val2_11_reg_684.read()) + sc_biguint<18>(zext_ln203_4_fu_384_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_2_fu_241_p1() {
    p_Val2_2_fu_241_p1 = esl_zext<18,17>(exp_res_1_V_reg_642.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_3_fu_254_p2() {
    p_Val2_3_fu_254_p2 = (!p_Val2_2_fu_241_p1.read().is_01() || !p_Val2_s_fu_238_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_Val2_2_fu_241_p1.read()) + sc_biguint<18>(p_Val2_s_fu_238_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_4_fu_244_p1() {
    p_Val2_4_fu_244_p1 = esl_zext<18,17>(exp_res_2_V_reg_648.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_5_fu_247_p1() {
    p_Val2_5_fu_247_p1 = esl_zext<18,17>(exp_res_3_V_reg_654.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_6_fu_276_p2() {
    p_Val2_6_fu_276_p2 = (!p_Val2_5_fu_247_p1.read().is_01() || !p_Val2_4_fu_244_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_Val2_5_fu_247_p1.read()) + sc_biguint<18>(p_Val2_4_fu_244_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_7_fu_268_p3() {
    p_Val2_7_fu_268_p3 = (!p_Result_s_fu_260_p3.read()[0].is_01())? sc_lv<18>(): ((p_Result_s_fu_260_p3.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_3_fu_254_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_8_fu_290_p3() {
    p_Val2_8_fu_290_p3 = (!p_Result_14_fu_282_p3.read()[0].is_01())? sc_lv<18>(): ((p_Result_14_fu_282_p3.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_6_fu_276_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_p_Val2_s_fu_238_p1() {
    p_Val2_s_fu_238_p1 = esl_zext<18,17>(exp_res_0_V_reg_636.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ret_V_1_fu_393_p2() {
    ret_V_1_fu_393_p2 = (!lhs_V_1_fu_387_p1.read().is_01() || !rhs_V_1_fu_390_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(lhs_V_1_fu_387_p1.read()) + sc_biguint<19>(rhs_V_1_fu_390_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ret_V_fu_304_p2() {
    ret_V_fu_304_p2 = (!lhs_V_fu_298_p1.read().is_01() || !rhs_V_fu_301_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(lhs_V_fu_298_p1.read()) + sc_bigint<19>(rhs_V_fu_301_p1.read()));
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_rhs_V_1_fu_390_p1() {
    rhs_V_1_fu_390_p1 = esl_zext<19,17>(exp_res_4_V_reg_677.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_rhs_V_fu_301_p1() {
    rhs_V_fu_301_p1 = esl_sext<19,18>(p_Val2_8_reg_671.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_select_ln340_3_fu_460_p3() {
    select_ln340_3_fu_460_p3 = (!xor_ln340_2_fu_432_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_2_fu_432_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_fu_450_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_select_ln340_fu_360_p3() {
    select_ln340_fu_360_p3 = (!xor_ln340_fu_342_p2.read()[0].is_01())? sc_lv<18>(): ((xor_ln340_fu_342_p2.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_10_fu_318_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_select_ln388_1_fu_468_p3() {
    select_ln388_1_fu_468_p3 = (!underflow_1_fu_426_p2.read()[0].is_01())? sc_lv<10>(): ((underflow_1_fu_426_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_fu_450_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_select_ln388_fu_368_p3() {
    select_ln388_fu_368_p3 = (!underflow_fu_336_p2.read()[0].is_01())? sc_lv<18>(): ((underflow_fu_336_p2.read()[0].to_bool())? ap_const_lv18_20000: p_Val2_10_fu_318_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_sext_ln1116_fu_488_p1() {
    sext_ln1116_fu_488_p1 = esl_sext<26,18>(inv_exp_sum_V_reg_700.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_tmp_fu_450_p4() {
    tmp_fu_450_p4 = p_Val2_14_fu_407_p2.read().range(17, 8);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_underflow_1_fu_426_p2() {
    underflow_1_fu_426_p2 = (p_Result_17_fu_399_p3.read() & xor_ln786_1_fu_420_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_underflow_fu_336_p2() {
    underflow_fu_336_p2 = (p_Result_15_fu_310_p3.read() & xor_ln786_fu_330_p2.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_xor_ln340_1_fu_348_p2() {
    xor_ln340_1_fu_348_p2 = (p_Result_15_fu_310_p3.read() ^ ap_const_lv1_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_xor_ln340_2_fu_432_p2() {
    xor_ln340_2_fu_432_p2 = (p_Result_17_fu_399_p3.read() ^ p_Result_18_fu_412_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_xor_ln340_3_fu_438_p2() {
    xor_ln340_3_fu_438_p2 = (p_Result_17_fu_399_p3.read() ^ ap_const_lv1_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_xor_ln340_fu_342_p2() {
    xor_ln340_fu_342_p2 = (p_Result_15_fu_310_p3.read() ^ p_Result_16_fu_322_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_xor_ln786_1_fu_420_p2() {
    xor_ln786_1_fu_420_p2 = (p_Result_18_fu_412_p3.read() ^ ap_const_lv1_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_xor_ln786_fu_330_p2() {
    xor_ln786_fu_330_p2 = (p_Result_16_fu_322_p3.read() ^ ap_const_lv1_1);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_y_V_1_fu_183_p4() {
    y_V_1_fu_183_p4 = data_1_V_read.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_y_V_2_fu_198_p4() {
    y_V_2_fu_198_p4 = data_2_V_read.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_y_V_3_fu_213_p4() {
    y_V_3_fu_213_p4 = data_3_V_read.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_y_V_5_fu_476_p3() {
    y_V_5_fu_476_p3 = (!or_ln340_1_fu_444_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_1_fu_444_p2.read()[0].to_bool())? select_ln340_3_fu_460_p3.read(): select_ln388_1_fu_468_p3.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_y_V_fu_168_p4() {
    y_V_fu_168_p4 = data_0_V_read.read().range(15, 6);
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_zext_ln203_4_fu_384_p1() {
    zext_ln203_4_fu_384_p1 = esl_zext<18,17>(exp_res_4_V_reg_677.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_zext_ln251_1_fu_193_p1() {
    zext_ln251_1_fu_193_p1 = esl_zext<64,10>(y_V_1_fu_183_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_zext_ln251_2_fu_208_p1() {
    zext_ln251_2_fu_208_p1 = esl_zext<64,10>(y_V_2_fu_198_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_zext_ln251_3_fu_223_p1() {
    zext_ln251_3_fu_223_p1 = esl_zext<64,10>(y_V_3_fu_213_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_zext_ln251_4_fu_250_p1() {
    zext_ln251_4_fu_250_p1 = esl_zext<64,10>(y_V_4_reg_631_pp0_iter1_reg.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_zext_ln251_fu_178_p1() {
    zext_ln251_fu_178_p1 = esl_zext<64,10>(y_V_fu_168_p4.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_zext_ln259_fu_484_p1() {
    zext_ln259_fu_484_p1 = esl_zext<64,10>(y_V_5_reg_690.read());
}

void softmax_latency_ap_fixed_ap_fixed_softmax_config13_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

