Backend: Pynq
ClockPeriod: 5
HLSConfig:
  LayerName:
    fc1:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 8
    fc1_input:
      Precision:
        result: ap_fixed<16,6>
    fc2:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 32
    fc3:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 16
    output:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 16
    relu1:
      Precision:
        result: ap_fixed<6,1>
      ReuseFactor: 1
    relu2:
      Precision:
        result: ap_fixed<6,1>
      ReuseFactor: 1
    relu3:
      Precision:
        result: ap_fixed<6,1>
      ReuseFactor: 1
    softmax:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Strategy: Stable
      exp_table_t: ap_fixed<18,6>
      inv_table_t: ap_fixed<18,4>
      table_size: 1024
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 64
    Strategy: Resource
IOType: io_parallel
Interface: s_axilite
KerasModel: !keras_model '/home/gabri-bot/University/Git_hub/PYNQ_IA/NN_train/HLS_projects/Qkeras_pruned/hls4ml_PYNQ_prj/keras_model.h5'
OutputDir: /home/gabri-bot/University/Git_hub/PYNQ_IA/NN_train/HLS_projects/Qkeras_pruned/hls4ml_PYNQ_prj
ProjectName: myproject
Stamp: 7AE8d9EC
XilinxPart: xc7z020clg400-1
